$P1$: /github/workspace/core/findAvailableDates.c File Reference
findAvailableDates.c File Reference
#include "sp1sLib.h"
Functions
int findSumAllEvents (const calendarSuite *suite)
Finds the sum of all events in a given calendarSuite.
void calSuiteToEventArray (const calendarSuite *suite, int sumAllEvents, int priority, event *eventPtrArray[])
Iterates through all events from all calendar-files and adds them all to one big array.
int startTimeCmp (const void *arg1, const void *arg2)
Compares two events to determine which event start the earliest.
int eventStartsEarlier (const event *event1, const event *event2)
Determines if event1 starts earlier than event2.
void printEventPtrArray (event *allEvents[], int n)
Prints all event data in a given array of pointer to events of length n.
tm lookForFreeSlot (const searchParameters *p, int arrLen, event *allEvents[])
Looks for a free time slot, defined by p, in a sorted array of pointers to events.
tm lookForFreeSlotSingle (const searchParameters *p, event *event, time_t *head)
Looks for a free time slot between head and event->startTime.
int endOfLine (const searchParameters *p, time_t head)
Controls that head has not gone over the final time, called endOfLine, where an event could be found as defined by p.
int canElongate (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head, const searchParameters *p)
Controls if head is considered able to elongate over event.
int canSwallow (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head)
Controls if head is considered able to swallow event.
int stuck (time_t eventStartTimeUnix, time_t head, const searchParameters *p)
Controls if head is considered stuck.
tm stuckProcedure (const searchParameters *p, time_t *head)
Runs the procedure corresponding to when head is considered stuck.
int headWithinLimits (const searchParameters *p, time_t head)
Controls that an event that starts at head, and is defined by p is within limits.
int tmWithinLimits (const searchParameters *p, const tm *time)
Controls that time is within lowerLimit and upperLimit defined in p.
void setHeadToNextLL (const searchParameters *p, time_t *head)
Sets head to be the next lowerLimit.
int overUpperLimit (const searchParameters *p, const tm *head_tm)
Controls if head_tm is over upperLimit.
int underLowerLimit (const searchParameters *p, const tm *head_tm)
Controls if head_tm is under lowerLimit.
void goToLowerLimitNextDay (time_t head, const searchParameters *p, tm *head_tm)
Sets head_tm to lowerLimit the next day.
void goToLowerLimitThisDay (const searchParameters *p, tm *head_tm)
Sets head_tm to lowerLimit same day.
time_t getStartOfLine (const searchParameters *p)
Finds the earliest time an event can take place, according to p.
time_t getEndOfLine (const searchParameters *p)
Finds the latest time an event can take place, according to p.
void print_time_t (time_t time)
Converts a time_t to a tm structure, prints the tm structure.
Variables
int DEBUG
Function Documentation
calSuiteToEventArray()
void calSuiteToEventArray (const calendarSuite * suite, int sumAllEvents, int priority, event * eventPtrArray[])
Iterates through all events from all calendar-files and adds them all to one big array.
The function loops through all calendars and adds all the events to one array. An event will only be added to the array if it has priority over the event we are finding an avaliable slot for.
Parameters
suite the suite of calendars to look through
eventPtrArray The array to put all events into
sumAllEvents The amount of events across all calendar files
priority The priority of the event the user wants to find an avaliable time slot for. Defaults to 1000
Definition at line 37 of file findAvailableDates.c.
{
     int i = 0, k;
     eventLink *cursor;
     for (k = 0; k < suite->Arraylen; k++) {
         cursor = suite->calPtrArray[k]->firstEvent;
         while (cursor != NULL) {
             if (cursor->currentEvent->priority <= priority) {
                 eventPtrArray[i] = cursor->currentEvent;
             } else {
                 eventPtrArray[i] = NULL;
             }
             cursor = cursor->nextEventLink;
             i++;
         }
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, eventLink::currentEvent, calendar::firstEvent, eventLink::nextEventLink, and event::priority.
Referenced by findAvailableDates().
canElongate()
int canElongate (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head, const searchParameters * p)
Controls if head is considered able to elongate over event.
Head is considered able to elongate if:
head is smaller than eventEndTimeUnix and head is larger than or equal to eventStartTimeUnix
head is smaller than eventStartTimeUnix, and the time between head and eventStartTimeUnix is smaller than: eventLen + buffer * 2 (unix time)
Parameters
eventStartTimeUnix Start of event in unix time.
eventEndTimeUnix End of event in unix time.
head Head to control.
p Search parameters, where eventLen and buffer are contained.
Returns
1 if it is able to elongate, else 0.
Precondition
MIN_TO_SEC should be #defined as 60.
Definition at line 251 of file findAvailableDates.c.
{
     return ((head < eventEndTimeUnix) && (head >= eventStartTimeUnix)) ||
            ((head < eventStartTimeUnix) && ((eventStartTimeUnix - head) < ((p->eventLen * MIN_TO_SEC) + (2 * p->buffer * MIN_TO_SEC))));
 }
References searchParameters::buffer, searchParameters::eventLen, and MIN_TO_SEC.
Referenced by lookForFreeSlotSingle(), test1_canElongate(), test2_canElongate(), and test3_canElongate().
canSwallow()
int canSwallow (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head)
Controls if head is considered able to swallow event.
Head is considered able to swallow event if: head is larger than eventStartTimeUnix and head is equal to or larger than eventEndTimeUnix.
Parameters
eventStartTimeUnix Start of event in unix time.
eventEndTimeUnix End of event in unix time.
head Head to control.
Returns
1 if head is able to swallow, else 0.
Definition at line 267 of file findAvailableDates.c.
{
     return (head >= eventEndTimeUnix) && (head > eventStartTimeUnix);
 }
Referenced by lookForFreeSlotSingle(), test1_canSwallow(), and test2_canSwallow().
endOfLine()
int endOfLine (const searchParameters * p, time_t head)
Controls that head has not gone over the final time, called endOfLine, where an event could be found as defined by p.
endOfLine is given by getEndOfLine().
Parameters
p Search parameters, where endOfLine can be found.
head time_t to control.
Returns
1 if head is a or over endOfLine.
Definition at line 230 of file findAvailableDates.c.
{
     time_t eolTime = getEndOfLine(p);
     return head >= eolTime;
 }
References getEndOfLine().
Referenced by lookForFreeSlotSingle(), test1_endOfLine(), and test2_endOfLine().
eventStartsEarlier()
int eventStartsEarlier (const event * event1, const event * event2)
Determines if event1 starts earlier than event2.
Parameters
event1 pointer to event structure
event2 pointer to event structure
Returns
int 1 if event1 ends later than event 2, 0 if event 2 ends later than event1 or they end at the same time
Definition at line 91 of file findAvailableDates.c.
{
     if (event1->startTime.tm_year > event2->startTime.tm_year) { /* Check year */
         return 1;
     } else if (event1->startTime.tm_year < event2->startTime.tm_year) {
         return 0;
     } else if (event1->startTime.tm_mon > event2->startTime.tm_mon) { /* Check month */
         return 1;
     } else if (event1->startTime.tm_year < event2->startTime.tm_year) {
         return 0;
     } else if (event1->startTime.tm_mday > event2->startTime.tm_mday) { /* Check day */
         return 1;
     } else if (event1->startTime.tm_mday < event2->startTime.tm_mday) {
         return 0;
     } else if (event1->startTime.tm_hour > event2->startTime.tm_hour) { /* Check hour */
         return 1;
     } else if (event1->startTime.tm_hour < event2->startTime.tm_hour) {
         return 0;
     } else if (event1->startTime.tm_min > event2->startTime.tm_min) { /* Check min */
         return 1;
     } else if (event1->startTime.tm_min < event2->startTime.tm_min) {
         return 0;
     } else if (event1->startTime.tm_sec > event2->startTime.tm_sec) { /* Check secs */
         return 1;
     } else {
         return 0;
     }
 }
References event::startTime.
Referenced by startTimeCmp(), test10_eventStartsEarlier(), test11_eventStartsEarlier(), test1_eventStartsEarlier(), test2_eventStartsEarlier(), test3_eventStartsEarlier(), test4_eventStartsEarlier(), test5_eventStartsEarlier(), test6_eventStartsEarlier(), test7_eventStartsEarlier(), test8_eventStartsEarlier(), and test9_eventStartsEarlier().
findSumAllEvents()
int findSumAllEvents (const calendarSuite * suite)
Finds the sum of all events in a given calendarSuite.
The sum is found by adding up all the sums found in suite->calPtrArray[i]->numOfEvents.
Parameters
suite calendarSuite where sum of all events should be found
Returns
sum of all events in calendarSuite
Definition at line 12 of file findAvailableDates.c.
{
     int i = 0, sum = 0;
     while (i < suite->Arraylen) {
         sum += suite->calPtrArray[i]->numOfEvents;
         i++;
     }
     return sum;
 }
References calendarSuite::calPtrArray, and calendar::numOfEvents.
Referenced by findAvailableDates().
getEndOfLine()
time_t getEndOfLine (const searchParameters * p)
Finds the latest time an event can take place, according to p.
Parameters
p Search parameters
Returns
Latest time an event can take place as a time_t.
Precondition
INIT_TM should be #defined as { 0, 0, 0, 1, 0, 0, 0, 0, -1 }.
Definition at line 472 of file findAvailableDates.c.
{
     tm time_tm = INIT_TM;
     time_t time;
     time_tm.tm_min = p->upperLimit.tm_min;
     time_tm.tm_hour = p->upperLimit.tm_hour;
     time_tm.tm_mday = p->endDate.tm_mday;
     time_tm.tm_mon = p->endDate.tm_mon;
     time_tm.tm_year = p->endDate.tm_year;
     time = mktime(&time_tm);
     return time;
 }
References searchParameters::endDate, INIT_TM, and searchParameters::upperLimit.
Referenced by endOfLine(), and test1_getEndOfLine().
getStartOfLine()
time_t getStartOfLine (const searchParameters * p)
Finds the earliest time an event can take place, according to p.
Parameters
p Search parameters
Returns
Latest time an event can take place as a time_t.
Precondition
INIT_TM should be #defined as { 0, 0, 0, 1, 0, 0, 0, 0, -1 }.
Definition at line 450 of file findAvailableDates.c.
{
     tm time_tm = INIT_TM;
     time_t time;
     time_tm.tm_min = p->lowerLimit.tm_min;
     time_tm.tm_hour = p->lowerLimit.tm_hour;
     time_tm.tm_mday = p->startDate.tm_mday;
     time_tm.tm_mon = p->startDate.tm_mon;
     time_tm.tm_year = p->startDate.tm_year;
     time = mktime(&time_tm);
     return time;
 }
References INIT_TM, searchParameters::lowerLimit, and searchParameters::startDate.
Referenced by lookForFreeSlot(), and test1_getStartOfLine().
goToLowerLimitNextDay()
void goToLowerLimitNextDay (time_t head, const searchParameters * p, tm * head_tm)
Sets head_tm to lowerLimit the next day.
Parameters
head head_tm in unix time
p Search paramters, where lowerLimit is defined.
[in,out] head_tm tm structure to change.
Precondition
UNIX_24H should be #defined as 60 * 60 * 24 or 86400.
Definition at line 426 of file findAvailableDates.c.
{
     head += UNIX_24H;
     *head_tm = *localtime(&head);
     goToLowerLimitThisDay(p, head_tm);
 }
References goToLowerLimitThisDay(), and UNIX_24H.
Referenced by setHeadToNextLL(), test1_goToLowerLimitNextDay(), test2_goToLowerLimitNextDay(), and test3_goToLowerLimitNextDay().
goToLowerLimitThisDay()
void goToLowerLimitThisDay (const searchParameters * p, tm * head_tm)
Sets head_tm to lowerLimit same day.
Parameters
p Search paramters, where lowerLimit is defined.
head_tm tm structure to change.
Definition at line 438 of file findAvailableDates.c.
{
     head_tm->tm_min = p->lowerLimit.tm_min;
     head_tm->tm_hour = p->lowerLimit.tm_hour;
 }
References searchParameters::lowerLimit.
Referenced by goToLowerLimitNextDay(), setHeadToNextLL(), and test1_goToLowerLimitThisDay().
headWithinLimits()
int headWithinLimits (const searchParameters * p, time_t head)
Controls that an event that starts at head, and is defined by p is within limits.
Parameters
p Search paramters, where limits are defined, and where event is defined.
head Start time of event.
Returns
1 if it is within limits, else 0.
Precondition
MIN_TO_SEC should be #defined as 60.
Definition at line 325 of file findAvailableDates.c.
{
     int returnFlag = 0;
     tm tm_headStart;
     tm tm_headEnd;
     time_t headEnd;
     headEnd = head + (p->eventLen * MIN_TO_SEC) + (2 * p->buffer * MIN_TO_SEC);
     tm_headStart = *localtime(&head);
     tm_headEnd = *localtime(&headEnd);
     returnFlag += tmWithinLimits(p, &tm_headStart);
     returnFlag += tmWithinLimits(p, &tm_headEnd);
     if (returnFlag == 2) {
         returnFlag = 1;
     } else {
         returnFlag = 0;
     }
     return returnFlag;
 }
References searchParameters::buffer, searchParameters::eventLen, MIN_TO_SEC, and tmWithinLimits().
Referenced by stuckProcedure(), test1_headWithinLimits(), and test2_headWithinLimits().
lookForFreeSlot()
tm lookForFreeSlot (const searchParameters * p, int arrLen, event * allEvents[])
Looks for a free time slot, defined by p, in a sorted array of pointers to events.
Iterating over allEvents, this functions looks a timeslot of lenght eventLen + buffer * 2 (in minutes). The function will keep looking until:
End of list is reached (i < arrLen && allEvents[i] != NULL) and
A date is found (dateFound.tm_year < 0)
head has not gone over endOfLine (dateFound.tm_year != eol)
Parameters
p Search parameters, controls what timeslot loofForFreeSlot should look for, and where it should look.
arrLen length of array allEvents
allEvents sorted array of pointers
Returns
If a date is found that date is returned as a tm structure. Else returns a date where .tm_year < 0.
Precondition
enum lookForFreeSlotStatus { eol = -1, endOfLine look = -2, redo = -3 }; should be in header. allEvents should be sorted in acending order by starting date.
Definition at line 152 of file findAvailableDates.c.
{
     time_t head = getStartOfLine(p);
     tm dateFound;
     int i = 0;
     dateFound.tm_year = look;
     while (i < arrLen && allEvents[i] != NULL && dateFound.tm_year < 0 && dateFound.tm_year != eol) {
         if (DEBUG) printf("Event: %s\n", allEvents[i]->title);
         dateFound = lookForFreeSlotSingle(p, allEvents[i], &head);
         if (DEBUG) {
             printf("head: ");
             print_time_t(head);
             printf("\n");
         }
         if (dateFound.tm_year != redo) {
             i++;
         }
     }
     return dateFound;
 }
References DEBUG, eol, getStartOfLine(), look, lookForFreeSlotSingle(), print_time_t(), and redo.
Referenced by findAvailableDates().
lookForFreeSlotSingle()
tm lookForFreeSlotSingle (const searchParameters * p, event * event, time_t * head)
Looks for a free time slot between head and event->startTime.
If head is at endOfLine: .tm_year in the return struct tm is set to eol. This causes lookForFreeSlot() to stop looking for an event.
Else if head is able to elongate, head elongates meaning head is set to event->endTime (in unix time). lookForFreeSlot() should then iterates to next event.
Else if head is able to swallow, head swallows meaning head is unchanged. lookForFreeSlot() should then iterates to next event.
Else if head is stuck, stuck mening it found a time slot of lenght greater than eventLen
buffer * 2, lookForFreeSlot() either does not iterate if date was not within limits as defined by p, or causes lookForFreeSlot() to stop looking as a date was found.
Parameters
p Search parameters.
event Pointer to event to compare.
[in,out] head Current head to compare and change.
Returns
If a date is found that date is returned as a tm structure. Else returns a date where .tm_year < 0.
Precondition
enum lookForFreeSlotStatus { eol = -1, endOfLine look = -2, redo = -3 }; should be in header.
Definition at line 199 of file findAvailableDates.c.
{
     time_t eventStartTimeUnix = mktime(&event->startTime);
     time_t eventEndTimeUnix = mktime(&event->endTime);
     tm dateFound;
     dateFound.tm_year = look;
     if (endOfLine(p, *head)) {
         if (DEBUG) printf("endOfLine\n");
         dateFound.tm_year = eol;
     } else if (canElongate(eventStartTimeUnix, eventEndTimeUnix, *head, p)) {
         if (DEBUG) printf("elongate\n");
         *head = eventEndTimeUnix;
     } else if (canSwallow(eventStartTimeUnix, eventEndTimeUnix, *head)) {
         if (DEBUG) printf("swallow\n");
     } else if (stuck(eventStartTimeUnix, *head, p)) {
         dateFound = stuckProcedure(p, head);
     }
     return dateFound;
 }
References canElongate(), canSwallow(), DEBUG, endOfLine(), event::endTime, eol, look, event::startTime, stuck(), and stuckProcedure().
Referenced by lookForFreeSlot().
overUpperLimit()
int overUpperLimit (const searchParameters * p, const tm * head_tm)
Controls if head_tm is over upperLimit.
Parameters
p Search paramters, where upperLimit is defined.
head_tm tm structure to control
Returns
1 if it is, else 0
Definition at line 391 of file findAvailableDates.c.
{
     if (head_tm->tm_hour > p->upperLimit.tm_hour) {
         return 1;
     } else if (head_tm->tm_hour == p->upperLimit.tm_hour && head_tm->tm_min > p->upperLimit.tm_min) {
         return 1;
     } else {
         return 0;
     }
 }
References searchParameters::upperLimit.
print_time_t()
void print_time_t (time_t time)
Converts a time_t to a tm structure, prints the tm structure.
Parameters
time time_t to print.
Precondition
EPOCH should be #defined as 1900.
Definition at line 493 of file findAvailableDates.c.
{
     tm *time_tm = localtime(&time);
     printf("%.2d/%.2d/%.2d - %.2d:%.2d\n",
            time_tm->tm_mday,
            time_tm->tm_mon + 1,
            time_tm->tm_year + EPOCH,
            time_tm->tm_hour,
            time_tm->tm_min);
 }
References EPOCH.
Referenced by lookForFreeSlot().
printEventPtrArray()
void printEventPtrArray (event * allEvents[], int n)
Prints all event data in a given array of pointer to events of length n.
Parameters
allEvents pointer to array of pointers to events
n length of array to be printed
Definition at line 125 of file findAvailableDates.c.
{
     int i;
     for (i = 0; i < n; i++) {
         if (allEvents[i] != NULL) {
             printEvent(allEvents[i]);
         }
     }
 }
References printEvent().
Referenced by findAvailableDates().
setHeadToNextLL()
void setHeadToNextLL (const searchParameters * p, time_t * head)
Sets head to be the next lowerLimit.
Parameters
p Search paramters, where lowerLimit is defined.
[in,out] head Head to set.
Definition at line 372 of file findAvailableDates.c.
{
     tm head_tm = *localtime(head);
     if (underLowerLimit(p, &head_tm)) {
         goToLowerLimitThisDay(p, &head_tm);
     } else {
         goToLowerLimitNextDay(*head, p, &head_tm);
     }
     *head = mktime(&head_tm);
 }
References goToLowerLimitNextDay(), goToLowerLimitThisDay(), and underLowerLimit().
Referenced by stuckProcedure().
startTimeCmp()
int startTimeCmp (const void * arg1, const void * arg2)
Compares two events to determine which event start the earliest.
Parameters
arg1 first event to be compared
arg2 second event to be compared
Returns
1 if the first event ends before the second, -1 if the second event ends before the first, 0 if both events end at the same time.
Definition at line 64 of file findAvailableDates.c.
{
     event **event1 = (event **)arg1;
     event **event2 = (event **)arg2;
     if (*event1 == NULL && *event2 != NULL) {
         return 1;
     } else if (*event1 != NULL && *event2 == NULL) {
         return -1;
     } else if (*event1 == NULL && *event2 == NULL) {
         return 0;
     } else if (eventStartsEarlier(*event1, *event2)) {
         return 1;
     } else if (eventStartsEarlier(*event2, *event1)) {
         return -1;
     } else {
         return 0;
     }
 }
References eventStartsEarlier().
Referenced by findAvailableDates().
stuck()
int stuck (time_t eventStartTimeUnix, time_t head, const searchParameters * p)
Controls if head is considered stuck.
Head is considered stuck if head is less than evenStartTimeUnix and the time between head and eventStartTimeUnix is greater or equal to: eventLen + buffer * 2 (unix time).
Parameters
eventStartTimeUnix Start time(unix) for an event.
head Head to control.
p Search parameters, where eventLen and buffer are contained.
Returns
1 if head is stuck, else 0.
Precondition
MIN_TO_SEC should be #defined as 60.
Definition at line 283 of file findAvailableDates.c.
{
     return ((head < eventStartTimeUnix) && ((eventStartTimeUnix - head) >= ((p->eventLen * MIN_TO_SEC) + (2 * p->buffer * MIN_TO_SEC))));
 }
References searchParameters::buffer, searchParameters::eventLen, and MIN_TO_SEC.
Referenced by lookForFreeSlotSingle().
stuckProcedure()
tm stuckProcedure (const searchParameters * p, time_t * head)
Runs the procedure corresponding to when head is considered stuck.
Checks if an event, as defined by p, starting at head is within limits, if this is the case the date is returned. Else head is set to the next lowerLimit, and returns tm date where .tm_year = redo.
Parameters
p Search parameters.
[in,out] head time_t to do the procedure on.
Returns
A valid tm time if a date is found within limits defined in p. Else if the date found is invalid i.e. not within the limits defined in p, returns tm date where .tm_year = redo.
Precondition
MIN_TO_SEC should be #defined as 60. enum redo should be equal to -3.
Definition at line 301 of file findAvailableDates.c.
{
     tm dateFound;
     if (headWithinLimits(p, *head)) {
         if (DEBUG) printf("found date\n");
         *head += p->buffer * MIN_TO_SEC;
         dateFound = *localtime(head);
     } else {
         if (DEBUG) printf("going to next lowerLimit\n");
         setHeadToNextLL(p, head);
         dateFound.tm_year = redo;
     }
     return dateFound;
 }
References searchParameters::buffer, DEBUG, headWithinLimits(), MIN_TO_SEC, redo, and setHeadToNextLL().
Referenced by lookForFreeSlotSingle().
tmWithinLimits()
int tmWithinLimits (const searchParameters * p, const tm * time)
Controls that time is within lowerLimit and upperLimit defined in p.
Parameters
p Search paramters, where lowerLimit and upperLimit is defined.
time tm struct to control.
Returns
1 if within the limits, else 0.
Definition at line 355 of file findAvailableDates.c.
{
     if (time->tm_hour > p->lowerLimit.tm_hour && time->tm_hour < p->upperLimit.tm_hour) {
         return 1;
     } else if ((time->tm_hour == p->lowerLimit.tm_hour && time->tm_min >= p->lowerLimit.tm_min) ||
                (time->tm_hour == p->upperLimit.tm_hour && time->tm_min <= p->upperLimit.tm_min)) {
         return 1;
     } else {
         return 0;
     }
 }
References searchParameters::lowerLimit, and searchParameters::upperLimit.
Referenced by headWithinLimits(), test1_tmWithinLimits(), test2_tmWithinLimits(), and test3_tmWithinLimits().
underLowerLimit()
int underLowerLimit (const searchParameters * p, const tm * head_tm)
Controls if head_tm is under lowerLimit.
Parameters
p Search paramters, where lowerLimit is defined.
head_tm tm structure to control
Returns
1 if it is, else 0
Definition at line 408 of file findAvailableDates.c.
{
     if (head_tm->tm_hour < p->lowerLimit.tm_hour) {
         return 1;
     } else if (head_tm->tm_hour == p->lowerLimit.tm_hour && head_tm->tm_min < p->lowerLimit.tm_min) {
         return 1;
     } else {
         return 0;
     }
 }
References searchParameters::lowerLimit.
Referenced by setHeadToNextLL(), test1_underLowerLimit(), test2_underLowerLimit(), and test3_underLowerLimit().
Variable Documentation
DEBUG
int DEBUG extern
Definition at line 2 of file main.c.
Referenced by lookForFreeSlot(), lookForFreeSlotSingle(), and stuckProcedure().