$P1$: /github/workspace/core/CuTest.h File Reference
CuTest.h File Reference
#include <setjmp.h>
#include <stdarg.h>
Data Structures
struct CuString
struct CuTest
struct CuSuite
Macros
#define CUTEST_VERSION "CuTest 1.5"
#define CU_ALLOC(TYPE) ((TYPE*) malloc(sizeof(TYPE)))
#define HUGE_STRING_LEN 8192
#define STRING_MAX 256
#define STRING_INC 256
#define CuFail(tc, ms) CuFail_Line((tc), __FILE__, __LINE__, NULL, (ms))
#define CuAssert(tc, ms, cond) CuAssert_Line((tc), __FILE__, __LINE__, (ms), (cond))
#define CuAssertTrue(tc, cond) CuAssert_Line((tc), __FILE__, __LINE__, "assert failed", (cond))
#define CuAssertStrEquals(tc, ex, ac) CuAssertStrEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
#define CuAssertStrEquals_Msg(tc, ms, ex, ac) CuAssertStrEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac))
#define CuAssertIntEquals(tc, ex, ac) CuAssertIntEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
#define CuAssertIntEquals_Msg(tc, ms, ex, ac) CuAssertIntEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac))
#define CuAssertDblEquals(tc, ex, ac, dl) CuAssertDblEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac),(dl))
#define CuAssertDblEquals_Msg(tc, ms, ex, ac, dl) CuAssertDblEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac),(dl))
#define CuAssertPtrEquals(tc, ex, ac) CuAssertPtrEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
#define CuAssertPtrEquals_Msg(tc, ms, ex, ac) CuAssertPtrEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac))
#define CuAssertPtrNotNull(tc, p) CuAssert_Line((tc),__FILE__,__LINE__,"null pointer unexpected",(p != NULL))
#define CuAssertPtrNotNullMsg(tc, msg, p) CuAssert_Line((tc),__FILE__,__LINE__,(msg),(p != NULL))
#define MAX_TEST_CASES 1024
#define SUITE_ADD_TEST(SUITE, TEST) CuSuiteAdd(SUITE, CuTestNew(#TEST, TEST))
Typedefs
typedef struct CuTest CuTest
typedef void(* TestFunction) (CuTest *)
Functions
char * CuStrAlloc (int size)
char * CuStrCopy (const char *old)
void CuStringInit (CuString *str)
CuString * CuStringNew (void)
void CuStringRead (CuString *str, const char *path)
void CuStringAppend (CuString *str, const char *text)
void CuStringAppendChar (CuString *str, char ch)
void CuStringAppendFormat (CuString *str, const char *format,...)
void CuStringInsert (CuString *str, const char *text, int pos)
void CuStringResize (CuString *str, int newSize)
void CuStringDelete (CuString *str)
void CuTestInit (CuTest *t, const char *name, TestFunction function)
CuTest * CuTestNew (const char *name, TestFunction function)
void CuTestRun (CuTest *tc)
void CuTestDelete (CuTest *t)
void CuFail_Line (CuTest *tc, const char *file, int line, const char *message2, const char *message)
void CuAssert_Line (CuTest *tc, const char *file, int line, const char *message, int condition)
void CuAssertStrEquals_LineMsg (CuTest *tc, const char *file, int line, const char *message, const char *expected, const char *actual)
void CuAssertIntEquals_LineMsg (CuTest *tc, const char *file, int line, const char *message, int expected, int actual)
void CuAssertDblEquals_LineMsg (CuTest *tc, const char *file, int line, const char *message, double expected, double actual, double delta)
void CuAssertPtrEquals_LineMsg (CuTest *tc, const char *file, int line, const char *message, void *expected, void *actual)
void CuSuiteInit (CuSuite *testSuite)
CuSuite * CuSuiteNew (void)
void CuSuiteDelete (CuSuite *testSuite)
void CuSuiteAdd (CuSuite *testSuite, CuTest *testCase)
void CuSuiteAddSuite (CuSuite *testSuite, CuSuite *testSuite2)
void CuSuiteRun (CuSuite *testSuite)
void CuSuiteSummary (CuSuite *testSuite, CuString *summary)
void CuSuiteDetails (CuSuite *testSuite, CuString *details)
Macro Definition Documentation
CU_ALLOC
#define CU_ALLOC (TYPE) ((TYPE*) malloc(sizeof(TYPE)))
Definition at line 14 of file CuTest.h.
CuAssert
#define CuAssert (tc, ms, cond) CuAssert_Line((tc), __FILE__, __LINE__, (ms), (cond))
Definition at line 77 of file CuTest.h.
CuAssertDblEquals
#define CuAssertDblEquals (tc, ex, ac, dl) CuAssertDblEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac),(dl))
Definition at line 84 of file CuTest.h.
CuAssertDblEquals_Msg
#define CuAssertDblEquals_Msg (tc, ms, ex, ac, dl) CuAssertDblEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac),(dl))
Definition at line 85 of file CuTest.h.
CuAssertIntEquals
#define CuAssertIntEquals (tc, ex, ac) CuAssertIntEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
Definition at line 82 of file CuTest.h.
CuAssertIntEquals_Msg
#define CuAssertIntEquals_Msg (tc, ms, ex, ac) CuAssertIntEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac))
Definition at line 83 of file CuTest.h.
CuAssertPtrEquals
#define CuAssertPtrEquals (tc, ex, ac) CuAssertPtrEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
Definition at line 86 of file CuTest.h.
CuAssertPtrEquals_Msg
#define CuAssertPtrEquals_Msg (tc, ms, ex, ac) CuAssertPtrEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac))
Definition at line 87 of file CuTest.h.
CuAssertPtrNotNull
#define CuAssertPtrNotNull (tc, p) CuAssert_Line((tc),__FILE__,__LINE__,"null pointer unexpected",(p != NULL))
Definition at line 89 of file CuTest.h.
CuAssertPtrNotNullMsg
#define CuAssertPtrNotNullMsg (tc, msg, p) CuAssert_Line((tc),__FILE__,__LINE__,(msg),(p != NULL))
Definition at line 90 of file CuTest.h.
CuAssertStrEquals
#define CuAssertStrEquals (tc, ex, ac) CuAssertStrEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
Definition at line 80 of file CuTest.h.
CuAssertStrEquals_Msg
#define CuAssertStrEquals_Msg (tc, ms, ex, ac) CuAssertStrEquals_LineMsg((tc),__FILE__,__LINE__,(ms),(ex),(ac))
Definition at line 81 of file CuTest.h.
CuAssertTrue
#define CuAssertTrue (tc, cond) CuAssert_Line((tc), __FILE__, __LINE__, "assert failed", (cond))
Definition at line 78 of file CuTest.h.
CuFail
#define CuFail (tc, ms) CuFail_Line((tc), __FILE__, __LINE__, NULL, (ms))
Definition at line 76 of file CuTest.h.
CUTEST_VERSION
#define CUTEST_VERSION "CuTest 1.5"
Definition at line 7 of file CuTest.h.
HUGE_STRING_LEN
#define HUGE_STRING_LEN 8192
Definition at line 16 of file CuTest.h.
MAX_TEST_CASES
#define MAX_TEST_CASES 1024
Definition at line 94 of file CuTest.h.
STRING_INC
#define STRING_INC 256
Definition at line 18 of file CuTest.h.
STRING_MAX
#define STRING_MAX 256
Definition at line 17 of file CuTest.h.
SUITE_ADD_TEST
#define SUITE_ADD_TEST (SUITE, TEST) CuSuiteAdd(SUITE, CuTestNew(#TEST, TEST))
Definition at line 96 of file CuTest.h.
Typedef Documentation
CuTest
typedef struct CuTest CuTest
Definition at line 39 of file CuTest.h.
TestFunction
typedef void(* TestFunction) (CuTest *)
Definition at line 41 of file CuTest.h.
Function Documentation
CuAssert_Line()
void CuAssert_Line (CuTest * tc, const char * file, int line, const char * message, int condition)
Definition at line 174 of file CuTest.c.
{
    if (condition) return;
    CuFail_Line(tc, file, line, NULL, message);
}
References CuFail_Line().
CuAssertDblEquals_LineMsg()
void CuAssertDblEquals_LineMsg (CuTest * tc, const char * file, int line, const char * message, double expected, double actual, double delta)
Definition at line 214 of file CuTest.c.
{
    char buf[STRING_MAX];
    if (fabs(expected - actual) <= delta) return;
    sprintf(buf, "expected <%f> but was <%f>", expected, actual);
    CuFail_Line(tc, file, line, message, buf);
}
References CuFail_Line(), and STRING_MAX.
CuAssertIntEquals_LineMsg()
void CuAssertIntEquals_LineMsg (CuTest * tc, const char * file, int line, const char * message, int expected, int actual)
Definition at line 205 of file CuTest.c.
{
    char buf[STRING_MAX];
    if (expected == actual) return;
    sprintf(buf, "expected <%d> but was <%d>", expected, actual);
    CuFail_Line(tc, file, line, message, buf);
}
References CuFail_Line(), and STRING_MAX.
CuAssertPtrEquals_LineMsg()
void CuAssertPtrEquals_LineMsg (CuTest * tc, const char * file, int line, const char * message, void * expected, void * actual)
Definition at line 224 of file CuTest.c.
{
    char buf[STRING_MAX];
    if (expected == actual) return;
    sprintf(buf, "expected pointer <0x%p> but was <0x%p>", expected, actual);
    CuFail_Line(tc, file, line, message, buf);
}
References CuFail_Line(), and STRING_MAX.
CuAssertStrEquals_LineMsg()
void CuAssertStrEquals_LineMsg (CuTest * tc, const char * file, int line, const char * message, const char * expected, const char * actual)
Definition at line 180 of file CuTest.c.
{
    CuString string;
    if ((expected == NULL && actual == NULL) ||
        (expected != NULL && actual != NULL &&
         strcmp(expected, actual) == 0))
    {
        return;
    }
    CuStringInit(&string);
    if (message != NULL)
    {
        CuStringAppend(&string, message);
        CuStringAppend(&string, ": ");
    }
    CuStringAppend(&string, "expected <");
    CuStringAppend(&string, expected);
    CuStringAppend(&string, "> but was <");
    CuStringAppend(&string, actual);
    CuStringAppend(&string, ">");
    CuFailInternal(tc, file, line, &string);
}
References CuStringAppend(), and CuStringInit().
CuFail_Line()
void CuFail_Line (CuTest * tc, const char * file, int line, const char * message2, const char * message)
Definition at line 160 of file CuTest.c.
{
    CuString string;
    CuStringInit(&string);
    if (message2 != NULL)
    {
        CuStringAppend(&string, message2);
        CuStringAppend(&string, ": ");
    }
    CuStringAppend(&string, message);
    CuFailInternal(tc, file, line, &string);
}
References CuStringAppend(), and CuStringInit().
Referenced by CuAssert_Line(), CuAssertDblEquals_LineMsg(), CuAssertIntEquals_LineMsg(), and CuAssertPtrEquals_LineMsg().
CuStrAlloc()
char * CuStrAlloc (int size)
Definition at line 14 of file CuTest.c.
{
    char* newStr = (char*) malloc( sizeof(char) * (size) );
    return newStr;
}
Referenced by CuStrCopy().
CuStrCopy()
char * CuStrCopy (const char * old)
Definition at line 20 of file CuTest.c.
{
    int len = strlen(old);
    char* newStr = CuStrAlloc(len + 1);
    strcpy(newStr, old);
    return newStr;
}
References CuStrAlloc().
Referenced by CuTestInit().
CuStringAppend()
void CuStringAppend (CuString * str, const char * text)
Definition at line 63 of file CuTest.c.
{
    int length;
    if (text == NULL) {
        text = "NULL";
    }
    length = strlen(text);
    if (str->length + length + 1 >= str->size)
        CuStringResize(str, str->length + length + 1 + STRING_INC);
    str->length += length;
    strcat(str->buffer, text);
}
References CuString::buffer, CuStringResize(), CuString::length, CuString::size, and STRING_INC.
Referenced by CuAssertStrEquals_LineMsg(), CuFail_Line(), CuStringAppendChar(), CuStringAppendFormat(), CuSuiteDetails(), and CuSuiteSummary().
CuStringAppendChar()
void CuStringAppendChar (CuString * str, char ch)
Definition at line 78 of file CuTest.c.
{
    char text[2];
    text[0] = ch;
    text[1] = '\0';
    CuStringAppend(str, text);
}
References CuStringAppend().
CuStringAppendFormat()
void CuStringAppendFormat (CuString * str, const char * format, ...)
Definition at line 86 of file CuTest.c.
{
    va_list argp;
    char buf[HUGE_STRING_LEN];
    va_start(argp, format);
    vsprintf(buf, format, argp);
    va_end(argp);
    CuStringAppend(str, buf);
}
References CuStringAppend(), and HUGE_STRING_LEN.
Referenced by CuSuiteDetails().
CuStringDelete()
void CuStringDelete (CuString * str)
Definition at line 50 of file CuTest.c.
{
        if (!str) return;
        free(str->buffer);
        free(str);
}
References CuString::buffer.
CuStringInit()
void CuStringInit (CuString * str)
Definition at line 32 of file CuTest.c.
{
    str->length = 0;
    str->size = STRING_MAX;
    str->buffer = (char*) malloc(sizeof(char) * str->size);
    str->buffer[0] = '\0';
}
References CuString::buffer, CuString::length, CuString::size, and STRING_MAX.
Referenced by CuAssertStrEquals_LineMsg(), and CuFail_Line().
CuStringInsert()
void CuStringInsert (CuString * str, const char * text, int pos)
Definition at line 96 of file CuTest.c.
{
    int length = strlen(text);
    if (pos > str->length)
        pos = str->length;
    if (str->length + length + 1 >= str->size)
        CuStringResize(str, str->length + length + 1 + STRING_INC);
    memmove(str->buffer + pos + length, str->buffer + pos, (str->length - pos) + 1);
    str->length += length;
    memcpy(str->buffer + pos, text, length);
}
References CuString::buffer, CuStringResize(), CuString::length, CuString::size, and STRING_INC.
CuStringNew()
CuString * CuStringNew (void)
Definition at line 40 of file CuTest.c.
{
    CuString* str = (CuString*) malloc(sizeof(CuString));
    str->length = 0;
    str->size = STRING_MAX;
    str->buffer = (char*) malloc(sizeof(char) * str->size);
    str->buffer[0] = '\0';
    return str;
}
References CuString::buffer, CuString::length, CuString::size, and STRING_MAX.
Referenced by runAllTests().
CuStringRead()
void CuStringRead (CuString * str, const char * path)
CuStringResize()
void CuStringResize (CuString * str, int newSize)
Definition at line 57 of file CuTest.c.
{
    str->buffer = (char*) realloc(str->buffer, sizeof(char) * newSize);
    str->size = newSize;
}
References CuString::buffer, and CuString::size.
Referenced by CuStringAppend(), and CuStringInsert().
CuSuiteAdd()
void CuSuiteAdd (CuSuite * testSuite, CuTest * testCase)
Definition at line 266 of file CuTest.c.
{
    assert(testSuite->count < MAX_TEST_CASES);
    testSuite->list[testSuite->count] = testCase;
    testSuite->count++;
}
References CuSuite::count, CuSuite::list, and MAX_TEST_CASES.
Referenced by CuSuiteAddSuite().
CuSuiteAddSuite()
void CuSuiteAddSuite (CuSuite * testSuite, CuSuite * testSuite2)
Definition at line 273 of file CuTest.c.
{
    int i;
    for (i = 0 ; i < testSuite2->count ; ++i)
    {
        CuTest* testCase = testSuite2->list[i];
        CuSuiteAdd(testSuite, testCase);
    }
}
References CuSuite::count, CuSuiteAdd(), and CuSuite::list.
Referenced by runAllTests().
CuSuiteDelete()
void CuSuiteDelete (CuSuite * testSuite)
Definition at line 252 of file CuTest.c.
{
        unsigned int n;
        for (n=0; n < MAX_TEST_CASES; n++)
        {
                if (testSuite->list[n])
                {
                        CuTestDelete(testSuite->list[n]);
                }
        }
        free(testSuite);
}
References CuTestDelete(), CuSuite::list, and MAX_TEST_CASES.
CuSuiteDetails()
void CuSuiteDetails (CuSuite * testSuite, CuString * details)
Definition at line 305 of file CuTest.c.
{
    int i;
    int failCount = 0;
    if (testSuite->failCount == 0)
    {
        int passCount = testSuite->count - testSuite->failCount;
        const char* testWord = passCount == 1 ? "test" : "tests";
        CuStringAppendFormat(details, "OK (%d %s)\n", passCount, testWord);
    }
    else
    {
        if (testSuite->failCount == 1)
            CuStringAppend(details, "There was 1 failure:\n");
        else
            CuStringAppendFormat(details, "There were %d failures:\n", testSuite->failCount);
        for (i = 0 ; i < testSuite->count ; ++i)
        {
            CuTest* testCase = testSuite->list[i];
            if (testCase->failed)
            {
                failCount++;
                CuStringAppendFormat(details, "%d) %s: %s\n",
                    failCount, testCase->name, testCase->message);
            }
        }
        CuStringAppend(details, "\n!!!FAILURES!!!\n");
        CuStringAppendFormat(details, "Runs: %d ",   testSuite->count);
        CuStringAppendFormat(details, "Passes: %d ", testSuite->count - testSuite->failCount);
        CuStringAppendFormat(details, "Fails: %d\n",  testSuite->failCount);
    }
}
References CuSuite::count, CuStringAppend(), CuStringAppendFormat(), CuSuite::failCount, CuTest::failed, CuSuite::list, CuTest::message, and CuTest::name.
Referenced by runAllTests().
CuSuiteInit()
void CuSuiteInit (CuSuite * testSuite)
Definition at line 238 of file CuTest.c.
{
    testSuite->count = 0;
    testSuite->failCount = 0;
        memset(testSuite->list, 0, sizeof(testSuite->list));
}
References CuSuite::count, CuSuite::failCount, and CuSuite::list.
Referenced by CuSuiteNew().
CuSuiteNew()
CuSuite * CuSuiteNew (void)
Definition at line 245 of file CuTest.c.
{
    CuSuite* testSuite = CU_ALLOC(CuSuite);
    CuSuiteInit(testSuite);
    return testSuite;
}
References CU_ALLOC, and CuSuiteInit().
Referenced by runAllTests(), suite_ctrlAndDoArgs(), suite_findAvaliableDates(), suite_getCalendarSuite(), and suite_sharedFunctions().
CuSuiteRun()
void CuSuiteRun (CuSuite * testSuite)
Definition at line 283 of file CuTest.c.
{
    int i;
    for (i = 0 ; i < testSuite->count ; ++i)
    {
        CuTest* testCase = testSuite->list[i];
        CuTestRun(testCase);
        if (testCase->failed) { testSuite->failCount += 1; }
    }
}
References CuSuite::count, CuTestRun(), CuSuite::failCount, CuTest::failed, and CuSuite::list.
Referenced by runAllTests().
CuSuiteSummary()
void CuSuiteSummary (CuSuite * testSuite, CuString * summary)
Definition at line 294 of file CuTest.c.
{
    int i;
    for (i = 0 ; i < testSuite->count ; ++i)
    {
        CuTest* testCase = testSuite->list[i];
        CuStringAppend(summary, testCase->failed ? "F" : ".");
    }
    CuStringAppend(summary, "\n\n");
}
References CuSuite::count, CuStringAppend(), CuTest::failed, and CuSuite::list.
Referenced by runAllTests().
CuTestDelete()
void CuTestDelete (CuTest * t)
Definition at line 129 of file CuTest.c.
{
        if (!t) return;
        free(t->name);
        free(t);
}
References CuTest::name.
Referenced by CuSuiteDelete().
CuTestInit()
void CuTestInit (CuTest * t, const char * name, TestFunction function)
Definition at line 112 of file CuTest.c.
{
    t->name = CuStrCopy(name);
    t->failed = 0;
    t->ran = 0;
    t->message = NULL;
    t->function = function;
    t->jumpBuf = NULL;
}
References CuStrCopy(), CuTest::failed, CuTest::function, CuTest::jumpBuf, CuTest::message, CuTest::name, and CuTest::ran.
Referenced by CuTestNew().
CuTestNew()
CuTest * CuTestNew (const char * name, TestFunction function)
Definition at line 122 of file CuTest.c.
{
    CuTest* tc = CU_ALLOC(CuTest);
    CuTestInit(tc, name, function);
    return tc;
}
References CU_ALLOC, and CuTestInit().
CuTestRun()
void CuTestRun (CuTest * tc)
Definition at line 136 of file CuTest.c.
{
    jmp_buf buf;
    tc->jumpBuf = &buf;
    if (setjmp(buf) == 0)
    {
        tc->ran = 1;
        (tc->function)(tc);
    }
    tc->jumpBuf = 0;
}
References CuTest::function, CuTest::jumpBuf, and CuTest::ran.
Referenced by CuSuiteRun().