$P1$: /github/workspace/core/getCalendarSuite.c File Reference
getCalendarSuite.c File Reference
#include "sp1sLib.h"
Functions
int getCalendarSuiteGetFile (int argc, char *argv[], calendar *calPtrArray[])
Opens and stores file-pointer and file-path in calPtrArray.
int getCalendarSuiteGetFileSingle (char arg[], calendar *calendar)
Tries to open arg as a file, stores the file-path and file-pointer in calendar.
int getCalendarSuiteGetData (calendarSuite *calendarSuite)
Builds a linked list of eventLinks, for each calendar pointed to by calendarSuite.calPtrArray.
int getCalendarSuiteGetDataSingle (calendar *calendar)
Builds a linked list from data pointed to by the FILE pointer file contained in calendar, makes calendar.firstEvent point to the first link/nodes in this linked list of eventLink.
void addEventCal (event *newEvent, calendar *inputCal)
Adds an eventLink pointing to newEvent to the end of the linked list that is inputCal.
eventLink * mallocEventLink (event *event, eventLink *pointer)
Creates a new eventLink.
Function Documentation
addEventCal()
void addEventCal (event * newEvent, calendar * inputCal)
Adds an eventLink pointing to newEvent to the end of the linked list that is inputCal.
Allocates space for the new eventLink, then goes to the bottom of the linked list inputCal and points the NULL pointer to the new eventLink.
Parameters
newEvent The new event to be added at the end of the linked list.
inputCal First element in the linked list where newEvent needs to be added.
Definition at line 160 of file getCalendarSuite.c.
{
    eventLink *cursor, *newLink;
    newLink = mallocEventLink(newEvent, NULL);
    if (inputCal->firstEvent == NULL) {
        inputCal->firstEvent = newLink;
    } else {
        cursor = inputCal->firstEvent;
        while (cursor->nextEventLink != NULL) {
            cursor = cursor->nextEventLink;
        }
        cursor->nextEventLink = newLink;
    }
}
References calendar::firstEvent, mallocEventLink(), and eventLink::nextEventLink.
Referenced by getCalendarSuiteGetDataSingle().
getCalendarSuiteGetData()
int getCalendarSuiteGetData (calendarSuite * calendarSuite)
Builds a linked list of eventLinks, for each calendar pointed to by calendarSuite.calPtrArray.
This functions will also fclose the filepointer stored in each calendarSuite, when it has read the data it needs.
Parameters
calendarSuite Suite of calendars from where the linked lists should be build.
Returns
Returns 1 if no error is found i files, else 0 (this is not implemented at the moment).
Definition at line 62 of file getCalendarSuite.c.
{
    int i = 0, errorFlag = 1;
    while (i < calendarSuite->Arraylen && errorFlag) {
        errorFlag = getCalendarSuiteGetDataSingle(calendarSuite->calPtrArray[i]);
        fclose(calendarSuite->calPtrArray[i]->file);
        i++;
    }
    return errorFlag;
}
References calendarSuite::calPtrArray, calendar::file, and getCalendarSuiteGetDataSingle().
Referenced by getCalendarSuite().
getCalendarSuiteGetDataSingle()
int getCalendarSuiteGetDataSingle (calendar * calendar)
Builds a linked list from data pointed to by the FILE pointer file contained in calendar, makes calendar.firstEvent point to the first link/nodes in this linked list of eventLink.
This functions scans through the file pointed to by the FILE pointer contained in calendar. For each events the functions reads allocates space for this data in the heap, and points to this data in the linked list that is created. The number of events in each calendar is calculated and stored in calendar.numOfEvents.
Parameters
calendar Calendar from where the linked list should be build from.
Returns
1.
Definition at line 87 of file getCalendarSuite.c.
{
    event *newEvent;
    int isEvent = 0, numOfEvents = 0;
    char line[LINE_LEN], leftOverGarbage[LINE_LEN];
    while (fgets(line, LINE_LEN, calendar->file)) {
        if (strstr(line, "BEGIN:VEVENT")) { /* Find linjer hvor et event starter */
            isEvent = 1;
            numOfEvents++;
            newEvent = (event *)malloc(sizeof(event));
        }
        if (isEvent) {
            int temp_year, temp_mon;
            newEvent->startTime.tm_isdst = 0;
            newEvent->endTime.tm_isdst = 0;
            sscanf(line, "SUMMARY: %[^\n]", newEvent->title); /* Reads every character until -1 (EOF) */
            sscanf(line, "DTSTART:%4d%2d%2dT%2d%2d%2d%s",
                   &temp_year,
                   &temp_mon,
                   &newEvent->startTime.tm_mday,
                   &newEvent->startTime.tm_hour,
                   &newEvent->startTime.tm_min,
                   &newEvent->startTime.tm_sec,
                   leftOverGarbage);
            newEvent->startTime.tm_year = temp_year - 1900;
            newEvent->startTime.tm_mon = temp_mon - 1;
            if (sscanf(line, "DESCRIPTION:%[0-9a-zA-Z ]", leftOverGarbage) && leftOverGarbage[0] != '$') {
                sscanf(line, "DESCRIPTION:$P%d$", &newEvent->priority);
            } else {
                sscanf(line, "DESCRIPTION:$P%d$", &newEvent->priority);
            }
            if (newEvent->priority < 0) {
                newEvent->priority = 0;
            } else if (newEvent->priority > MAX_PRIORITY) {
                newEvent->priority = 0;
            }
            sscanf(line, "DTEND:%4d%2d%2dT%2d%2d%2d%s",
                   &temp_year,
                   &temp_mon,
                   &newEvent->endTime.tm_mday,
                   &newEvent->endTime.tm_hour,
                   &newEvent->endTime.tm_min,
                   &newEvent->endTime.tm_sec,
                   leftOverGarbage);
            newEvent->endTime.tm_year = temp_year - 1900;
            newEvent->endTime.tm_mon = temp_mon - 1;
        }
        if (strstr(line, "END:VEVENT")) {
            addEventCal(newEvent, calendar);
            isEvent = 0;
        }
    }
    calendar->numOfEvents = numOfEvents;
    return 1;
}
References addEventCal(), calendar::file, LINE_LEN, MAX_PRIORITY, and calendar::numOfEvents.
Referenced by getCalendarSuiteGetData().
getCalendarSuiteGetFile()
int getCalendarSuiteGetFile (int argc, char * argv[], calendar * calPtrArray[])
Opens and stores file-pointer and file-path in calPtrArray.
Goes through argc number of arguments argv, if the argv is an *.ics file tries to open the file. The file-path, and file-pointer is stored in calPtrArray, for each *.ics file.
Parameters
argc Number of arguments.
argv Arguments.
calPtrArray Output parameter.
Returns
1 if all file locations where valid, else 0.
Definition at line 14 of file getCalendarSuite.c.
{
    int i = 1;
    int k = 0;
    int validFileLocation = 1;
    do {
        if (isIcsFile(argv[i])) {
            validFileLocation = getCalendarSuiteGetFileSingle(argv[i], calPtrArray[k]);
            k++;
        }
        i++;
    } while (i < argc && validFileLocation);
    return validFileLocation;
}
References getCalendarSuiteGetFileSingle(), and isIcsFile().
Referenced by getCalendarSuite(), test1_getCalendarSuiteGetFile(), and test2_getCalendarSuiteGetFile().
getCalendarSuiteGetFileSingle()
int getCalendarSuiteGetFileSingle (char arg[], calendar * calendar)
Tries to open arg as a file, stores the file-path and file-pointer in calendar.
Parameters
arg File-path to an *.ics file.
calendar Output parameter, where file-path and file-pointer should be stored.
Returns
1 if file-path was valid, else 0.
Definition at line 37 of file getCalendarSuite.c.
{
    int validFileLocation = 0;
    calendar->file = fopen(arg, "r");
    strcpy(calendar->fileName, arg);
    if (calendar->file == NULL) {
        validFileLocation = 0;
    } else {
        validFileLocation = 1;
    }
    return validFileLocation;
}
References calendar::file, and calendar::fileName.
Referenced by getCalendarSuiteGetFile(), test1_getCalendarSuiteGetFileSingle(), and test2_getCalendarSuiteGetFileSingle().
mallocEventLink()
eventLink * mallocEventLink (event * event, eventLink * pointer)
Creates a new eventLink.
Allocates space on the heap for a new evenLink, makes the eventLink point to event, and pointer.
Parameters
event Event this link should point to.
pointer Next link this link should point to.
Returns
Pointer to the new eventLink that has been created.
Definition at line 185 of file getCalendarSuite.c.
{
    eventLink *newLink;
    newLink = (eventLink *)malloc(sizeof(eventLink));
    newLink->currentEvent = event;
    /*newLink->nextEventLink = (eventLink *)malloc(sizeof(eventLink));*/ /* <----- this is unnecessary*/
    newLink->nextEventLink = pointer;
    return newLink;
}
References eventLink::currentEvent, and eventLink::nextEventLink.
Referenced by addEventCal().