$P1$: /github/workspace/core/getSearchParameters.c File Reference
getSearchParameters.c File Reference
#include "sp1sLib.h"
Functions
int getPriority (void)
Get the Priority object.
int getEventLen (void)
Get the Event Len object.
int getEventBuffer (void)
Prompts user: Enter how much buffer time should be in beginning and end of event.
void getDates (tm *startDate, tm *endDate)
Get the Dates object.
void getLimits (tm *lowerLimmit, tm *upperLimit)
Get the Limits object.
Variables
int DEBUG
Function Documentation
getDates()
void getDates (tm * startDate, tm * endDate)
Get the Dates object.
First we ask for a start date, and reuce the value by 1. We do this because tm_mon in the tm struct, uses months after january, so if we want the event to start in february, the input needs to be 1 because february is one month after january. We do this for the enddate for the event as well. And to end it off we print the dates and confirm the start- and end dates.
Parameters
startDate
endDate
Definition at line 76 of file getSearchParameters.c.
{
     int validInput = 0;
     tm tempStartDate = INIT_TM;
     tm tempEndDate = INIT_TM;
     do {
         printf("Enter the earliest date the event can take place in the format: dd/mm/yyyy> ");
         scanf(" %d/%d/%d", &tempStartDate.tm_mday, &tempStartDate.tm_mon, &tempStartDate.tm_year);
         tempStartDate.tm_mon--;
         tempStartDate.tm_year = tempStartDate.tm_year - EPOCH;
         validInput = isTimeValid(tempStartDate);
         fflush(stdin);
     } while (!validInput);
     do {
         printf("Enter the latest date the event can take place in the format: dd/mm/yyyy> ");
         scanf(" %d/%d/%d", &tempEndDate.tm_mday, &tempEndDate.tm_mon, &tempEndDate.tm_year);
         tempEndDate.tm_mon--;
         tempEndDate.tm_year = tempEndDate.tm_year - EPOCH;
         validInput = isTimeValid(tempEndDate);
         fflush(stdin);
     } while (!validInput);
     if (DEBUG) {
         printf("tempStartDate: %.2d/%.2d/%.4d\n", tempStartDate.tm_mday, tempStartDate.tm_mon, tempStartDate.tm_year + EPOCH);
         printf("tempEndDate: %.2d/%.2d/%.4d\n", tempEndDate.tm_mday, tempEndDate.tm_mon, tempEndDate.tm_year + EPOCH);
     }
     *startDate = tempStartDate;
     *endDate = tempEndDate;
 }
References DEBUG, EPOCH, INIT_TM, and isTimeValid().
Referenced by getSearchParameters().
getEventBuffer()
int getEventBuffer (void)
Prompts user: Enter how much buffer time should be in beginning and end of event.
Input by user can not be under 0.
Returns
buffer entered.
Definition at line 51 of file getSearchParameters.c.
{
     int eventBuffer = 0;
     int validInput = 0;
     do {
         printf("Enter how much buffer time should be in beginning and end of event in minutes> ");
         validInput = scanf(" %d", &eventBuffer);
         fflush(stdin);
     } while (!validInput || eventBuffer < 0);
     return eventBuffer;
 }
Referenced by getSearchParameters().
getEventLen()
int getEventLen (void)
Get the Event Len object.
Here we ask for the length of the event in minutes, and check if it's a valid and positiv input we are getting. If yes, then we return the length from the function.
Returns
int
Definition at line 32 of file getSearchParameters.c.
                       {
     int eventLen = 0;
     int validInput = 0;
     do {
         printf("Enter estimated length of the event in minutes> ");
         validInput = scanf(" %d", &eventLen);
         fflush(stdin);
     } while (!validInput || eventLen < 0);
     return eventLen;
 }
Referenced by getSearchParameters().
getLimits()
void getLimits (tm * lowerLimmit, tm * upperLimit)
Get the Limits object.
Here we ask how much the event can be moved witin the same day, so only hours and minutes. We do this for both the upper- and lower limit. And at the end of the function we print, and confirm the upper- and lower limit.
Parameters
upperLimit
lowerLimmit
Definition at line 118 of file getSearchParameters.c.
{
     int validInput = 0;
     tm tempLowerLimit = INIT_TM;
     tm tempUpperLimit = INIT_TM;
     do {
         printf("Enter the earliest time the event can take place in the format: HH:MM>  ");
         scanf(" %d:%d", &tempLowerLimit.tm_hour, &tempLowerLimit.tm_min);
         validInput = isTimeValid(tempLowerLimit);
         fflush(stdin);
     } while (!validInput);
     do {
         printf("Enter the latest time the event can take place in the format: HH:MM>  ");
         scanf(" %d:%d", &tempUpperLimit.tm_hour, &tempUpperLimit.tm_min);
         validInput = isTimeValid(tempUpperLimit);
         fflush(stdin);
     } while (!validInput);
     if (DEBUG) {
         printf("%.2d:%.2d\n", tempLowerLimit.tm_hour, tempLowerLimit.tm_min);
         printf("%.2d:%.2d\n", tempUpperLimit.tm_hour, tempUpperLimit.tm_min);
     }
     *lowerLimmit = tempLowerLimit;
     *upperLimit = tempUpperLimit;
 }
References DEBUG, INIT_TM, and isTimeValid().
Referenced by getSearchParameters().
getPriority()
int getPriority (void)
Get the Priority object.
Here we ask for a priority for the event. Once the user has given us a valid input, then we return the priority from the function.
Returns
int
Definition at line 12 of file getSearchParameters.c.
                       {
     int priority = 0;
     int validInput = 0;
     do {
         printf("Enter a priority for the event> ");
         validInput = scanf(" %d", &priority);
         fflush(stdin);
     } while (!validInput || priority < 0);
     return priority;
 }
Referenced by getSearchParameters().
Variable Documentation
DEBUG
int DEBUG extern
Definition at line 2 of file main.c.
Referenced by getDates(), and getLimits().