.TH "C:/dev/P1/core/calendar.h" 3 "Thu Nov 26 2020" "$P1$" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/dev/P1/core/calendar.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBevent\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtm\fP \fBtm\fP"
.br
.ti -1c
.RI "typedef struct \fBevent\fP \fBevent\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBevent\fP \fBevent\fP"

.SS "typedef struct \fBtm\fP \fBtm\fP"

.PP
Definition at line 1 of file calendar\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for $P1$ from the source code\&.
