.TH "event" 3 "Thu Nov 26 2020" "$P1$" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <calendar\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [40]"
.br
.ti -1c
.RI "char \fBdescription\fP [280]"
.br
.ti -1c
.RI "\fBtm\fP \fBstartTime\fP"
.br
.ti -1c
.RI "\fBtm\fP \fBendTime\fP"
.br
.ti -1c
.RI "char \fBtags\fP [100][5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file calendar\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char description[280]"

.PP
Definition at line 5 of file calendar\&.h\&.
.SS "\fBtm\fP endTime"

.PP
Definition at line 7 of file calendar\&.h\&.
.SS "char name[40]"

.PP
Definition at line 4 of file calendar\&.h\&.
.SS "\fBtm\fP startTime"

.PP
Definition at line 6 of file calendar\&.h\&.
.SS "char tags[100][5]"

.PP
Definition at line 8 of file calendar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for $P1$ from the source code\&.
