.TH "C:/dev/P1/core/main.c" 3 "Thu Nov 26 2020" "$P1$" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/dev/P1/core/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'calendar\&.h'\fP
.br
\fC#include 'parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcheckArgs\fP (int)"
.br
.ti -1c
.RI "void \fBgetSearchParameters\fP (void)"
.br
.ti -1c
.RI "void \fBgetCalenderSuite\fP (void)"
.br
.ti -1c
.RI "int \fBfindAvailableDatesByLooking\fP (void)"
.br
.ti -1c
.RI "void \fBfindAvailableDatesByRestructuring\fP (void)"
.br
.ti -1c
.RI "void \fBuserOutput\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void checkArgs (int argc)"

.PP
Definition at line 45 of file main\&.c\&.
.SS "int findAvailableDatesByLooking (void)"

.PP
Definition at line 58 of file main\&.c\&.
.SS "void findAvailableDatesByRestructuring (void)"

.PP
Definition at line 62 of file main\&.c\&.
.SS "void getCalenderSuite (void)"

.PP
Definition at line 55 of file main\&.c\&.
.SS "void getSearchParameters (void)"

.PP
Definition at line 52 of file main\&.c\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 16 of file main\&.c\&.
.SS "void userOutput (void)"

.PP
Definition at line 65 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for $P1$ from the source code\&.
