.TH "C:/dev/P1/core/parser.c" 3 "Thu Nov 26 2020" "$P1$" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/dev/P1/core/parser.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLINE_LEN\fP   512"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparse_file\fP (char *file_path)"
.br
.RI "Takes a char-pointer for the file path to the file, which will be parsed, and prints all calendar-events and the number of evetns\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LINE_LEN   512"

.PP
Definition at line 5 of file parser\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int parse_file (char * file_path)"

.PP
Takes a char-pointer for the file path to the file, which will be parsed, and prints all calendar-events and the number of evetns\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile_path\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 14 of file parser\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for $P1$ from the source code\&.
