$P1$: /github/workspace/core/allTests.c File Reference
allTests.c File Reference
#include "sp1sLib.h"
Functions
void runAllTests (void)
void test1_doArg (CuTest *tc)
void test2_doArg (CuTest *tc)
void test3_doArg (CuTest *tc)
CuSuite * suite_ctrlAndDoArgs (void)
void test1_getCalendarSuiteGetFile (CuTest *tc)
void test2_getCalendarSuiteGetFile (CuTest *tc)
void test1_getCalendarSuiteGetFileSingle (CuTest *tc)
void test2_getCalendarSuiteGetFileSingle (CuTest *tc)
CuSuite * suite_getCalendarSuite (void)
void test1_isTimeValid (CuTest *tc)
void test2_isTimeValid (CuTest *tc)
void test3_isTimeValid (CuTest *tc)
void test4_isTimeValid (CuTest *tc)
void test5_isTimeValid (CuTest *tc)
void test6_isTimeValid (CuTest *tc)
void test7_isTimeValid (CuTest *tc)
void test8_isTimeValid (CuTest *tc)
void test9_isTimeValid (CuTest *tc)
void test10_isTimeValid (CuTest *tc)
CuSuite * suite_sharedFunctions (void)
Variables
int DEBUG
Function Documentation
runAllTests()
void runAllTests (void)
Definition at line 5 of file allTests.c.
{
     CuString *output = CuStringNew();
     CuSuite *suite = CuSuiteNew();
     CuSuiteAddSuite(suite, suite_ctrlAndDoArgs());
     CuSuiteAddSuite(suite, suite_getCalendarSuite());
     CuSuiteAddSuite(suite, suite_sharedFunctions());
     CuSuiteRun(suite);
     CuSuiteSummary(suite, output);
     CuSuiteDetails(suite, output);
     printf("%s\n", output->buffer);
 }
References CuString::buffer, CuStringNew(), CuSuiteAddSuite(), CuSuiteDetails(), CuSuiteNew(), CuSuiteRun(), CuSuiteSummary(), suite_ctrlAndDoArgs(), suite_getCalendarSuite(), and suite_sharedFunctions().
Referenced by doOption().
suite_ctrlAndDoArgs()
CuSuite* suite_ctrlAndDoArgs (void)
Definition at line 43 of file allTests.c.
{
     CuSuite *suite = CuSuiteNew();
     SUITE_ADD_TEST(suite, test1_doArg);
     SUITE_ADD_TEST(suite, test2_doArg);
     SUITE_ADD_TEST(suite, test3_doArg);
     return suite;
 }
References CuSuiteNew(), SUITE_ADD_TEST, test1_doArg(), test2_doArg(), and test3_doArg().
Referenced by runAllTests().
suite_getCalendarSuite()
CuSuite* suite_getCalendarSuite (void)
Definition at line 97 of file allTests.c.
{
     CuSuite *suite = CuSuiteNew();
     SUITE_ADD_TEST(suite, test1_getCalendarSuiteGetFile);
     SUITE_ADD_TEST(suite, test2_getCalendarSuiteGetFile);
     SUITE_ADD_TEST(suite, test1_getCalendarSuiteGetFileSingle);
     SUITE_ADD_TEST(suite, test2_getCalendarSuiteGetFileSingle);
     return suite;
 }
References CuSuiteNew(), SUITE_ADD_TEST, test1_getCalendarSuiteGetFile(), test1_getCalendarSuiteGetFileSingle(), test2_getCalendarSuiteGetFile(), and test2_getCalendarSuiteGetFileSingle().
Referenced by runAllTests().
suite_sharedFunctions()
CuSuite* suite_sharedFunctions (void)
Definition at line 179 of file allTests.c.
{
     CuSuite *suite = CuSuiteNew();
     SUITE_ADD_TEST(suite, test1_isTimeValid);
     SUITE_ADD_TEST(suite, test2_isTimeValid);
     SUITE_ADD_TEST(suite, test3_isTimeValid);
     SUITE_ADD_TEST(suite, test4_isTimeValid);
     SUITE_ADD_TEST(suite, test5_isTimeValid);
     SUITE_ADD_TEST(suite, test6_isTimeValid);
     SUITE_ADD_TEST(suite, test7_isTimeValid);
     SUITE_ADD_TEST(suite, test8_isTimeValid);
     SUITE_ADD_TEST(suite, test9_isTimeValid);
     SUITE_ADD_TEST(suite, test10_isTimeValid);
     return suite;
 }
References CuSuiteNew(), SUITE_ADD_TEST, test10_isTimeValid(), test1_isTimeValid(), test2_isTimeValid(), test3_isTimeValid(), test4_isTimeValid(), test5_isTimeValid(), test6_isTimeValid(), test7_isTimeValid(), test8_isTimeValid(), and test9_isTimeValid().
Referenced by runAllTests().
test10_isTimeValid()
void test10_isTimeValid (CuTest * tc)
Definition at line 172 of file allTests.c.
{
     tm input = {0, 61, 25, 1, 0, 2000, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test1_doArg()
void test1_doArg (CuTest * tc)
Definition at line 22 of file allTests.c.
{
     char input[] = "test";
     int actual = doArg(input);
     int expected = invalid;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, doArg(), and invalid.
Referenced by suite_ctrlAndDoArgs().
test1_getCalendarSuiteGetFile()
void test1_getCalendarSuiteGetFile (CuTest * tc)
Definition at line 54 of file allTests.c.
{
     int actual;
     int expected;
     int input1 = 4;
     char *input2[] = {"a", ".\\sample-ics-files\\cal1.ics", ".\\sample-ics-files\\cal2.ics", ".\\sample-ics-files\\cal3.ics"};
     calendarSuite input3;
     mallocCalendarSuite(3, &input3);
     actual = getCalendarSuiteGetFile(input1, input2, input3.calPtrArray);
     expected = 1;
     free(input3.calPtrArray);
     CuAssertIntEquals(tc, expected, actual);
 }
References calendarSuite::calPtrArray, CuAssertIntEquals, getCalendarSuiteGetFile(), and mallocCalendarSuite().
Referenced by suite_getCalendarSuite().
test1_getCalendarSuiteGetFileSingle()
void test1_getCalendarSuiteGetFileSingle (CuTest * tc)
Definition at line 81 of file allTests.c.
{
     char input1[] = ".\\sample-ics-files\\cal1.ics";
     calendar input2;
     int actual = getCalendarSuiteGetFileSingle(input1, &input2);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and getCalendarSuiteGetFileSingle().
Referenced by suite_getCalendarSuite().
test1_isTimeValid()
void test1_isTimeValid (CuTest * tc)
Definition at line 109 of file allTests.c.
{
     tm input = INIT_TM;
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, INIT_TM, and isTimeValid().
Referenced by suite_sharedFunctions().
test2_doArg()
void test2_doArg (CuTest * tc)
Definition at line 29 of file allTests.c.
{
     char input[] = "--doNothing";
     int actual = doArg(input);
     int expected = option;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, doArg(), and option.
Referenced by suite_ctrlAndDoArgs().
test2_getCalendarSuiteGetFile()
void test2_getCalendarSuiteGetFile (CuTest * tc)
Definition at line 67 of file allTests.c.
{
     int actual;
     int expected;
     int input1 = 4;
     char *input2[] = {"a", ".\\sample-ics-files\\notAValidFileLocation.ics", ".\\sample-ics-files\\cal2.ics", ".\\sample-ics-files\\cal3.ics"};
     calendarSuite input3;
     mallocCalendarSuite(3, &input3);
     actual = getCalendarSuiteGetFile(input1, input2, input3.calPtrArray);
     expected = 0;
     free(input3.calPtrArray);
     CuAssertIntEquals(tc, expected, actual);
 }
References calendarSuite::calPtrArray, CuAssertIntEquals, getCalendarSuiteGetFile(), and mallocCalendarSuite().
Referenced by suite_getCalendarSuite().
test2_getCalendarSuiteGetFileSingle()
void test2_getCalendarSuiteGetFileSingle (CuTest * tc)
Definition at line 89 of file allTests.c.
{
     char input1[] = ".\\sample-ics-files\\notAValidFileLocation.ics";
     calendar input2;
     int actual = getCalendarSuiteGetFileSingle(input1, &input2);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and getCalendarSuiteGetFileSingle().
Referenced by suite_getCalendarSuite().
test2_isTimeValid()
void test2_isTimeValid (CuTest * tc)
Definition at line 116 of file allTests.c.
{
     tm input = {0, 25, 20, 16, 4, 2009, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test3_doArg()
void test3_doArg (CuTest * tc)
Definition at line 36 of file allTests.c.
{
     char input[] = "*.ics";
     int actual = doArg(input);
     int expected = icsFile;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, doArg(), and icsFile.
Referenced by suite_ctrlAndDoArgs().
test3_isTimeValid()
void test3_isTimeValid (CuTest * tc)
Definition at line 123 of file allTests.c.
{
     tm input = {0, 0, 0, 29, 2, 2004, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test4_isTimeValid()
void test4_isTimeValid (CuTest * tc)
Definition at line 130 of file allTests.c.
{
     tm input = {0, 0, 0, 30, 1, 2004, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test5_isTimeValid()
void test5_isTimeValid (CuTest * tc)
Definition at line 137 of file allTests.c.
{
     tm input = {0, 0, 0, 28, 1, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test6_isTimeValid()
void test6_isTimeValid (CuTest * tc)
Definition at line 144 of file allTests.c.
{
     tm input = {0, 0, 0, 31, 0, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test7_isTimeValid()
void test7_isTimeValid (CuTest * tc)
Definition at line 151 of file allTests.c.
{
     tm input = {0, 0, 0, 32, 0, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test8_isTimeValid()
void test8_isTimeValid (CuTest * tc)
Definition at line 158 of file allTests.c.
{
     tm input = {0, 0, 0, 30, 3, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test9_isTimeValid()
void test9_isTimeValid (CuTest * tc)
Definition at line 165 of file allTests.c.
{
     tm input = {0, 0, 0, 31, 3, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
Variable Documentation
DEBUG
int DEBUG extern
Definition at line 2 of file main.c.