$P1$: /github/workspace/core/ctrlAndDoArgs.c File Reference
ctrlAndDoArgs.c File Reference
#include "sp1sLib.h"
Functions
int doArg (char arg[])
Controls what a command line argument is considered, and executes options if command line argument is an option.
int isOption (char arg[])
Controls if a string is considered an option from the command line.
int isIcsFile (char arg[])
Controls that a string ends with ".ics".
void doOption (char arg[])
Executes an option.
void exitWithError (void)
Displays error message and terminates the program.
Variables
int DEBUG
Function Documentation
doArg()
int doArg (char arg[])
Controls what a command line argument is considered, and executes options if command line argument is an option.
Parameters
arg argument to be controlled
Returns
enum icsFile if the argument is an *.ics file, enum option if the argument is an option, else enum invalid.
Definition at line 12 of file ctrlAndDoArgs.c.
                       {
     if (isIcsFile(arg)) {
         return icsFile;
     } else if (isOption(arg)) {
         doOption(arg);
         return option;
     } else {
         return invalid;
     }
 }
References doOption(), icsFile, invalid, isIcsFile(), isOption(), and option.
Referenced by ctrlAndDoArgs(), test1_doArg(), test2_doArg(), and test3_doArg().
doOption()
void doOption (char arg[])
Executes an option.
Parameters
arg string of option to be executed
Definition at line 62 of file ctrlAndDoArgs.c.
{
     if (strncmp(arg, "--test", 6) == 0) {
         runAllTests();
         exit(EXIT_SUCCESS);
     } else if (strncmp(arg, "--debug", 7) == 0) {
         DEBUG = 1;
     } else if (strncmp(arg, "--doNothing", 11) == 0) {
         /* do nothing */
     }
 }
References DEBUG, and runAllTests().
Referenced by doArg().
exitWithError()
void exitWithError (void)
Displays error message and terminates the program.
Definition at line 76 of file ctrlAndDoArgs.c.
{
     printf("Invalid argument, Please provide one or more .ics files\n");
     exit(EXIT_FAILURE);
 }
Referenced by ctrlAndDoArgs().
isIcsFile()
int isIcsFile (char arg[])
Controls that a string ends with ".ics".
Parameters
arg string to control
Returns
1 if it does end with ".ics", else 0
Definition at line 49 of file ctrlAndDoArgs.c.
{
     if ((strlen(arg)) < 5) {
         return 0;
     } else {
         return (strncmp(&arg[strlen(arg) - 4], ".ics", 4) == 0);
     }
 }
Referenced by doArg(), and getCalendarSuiteGetFile().
isOption()
int isOption (char arg[])
Controls if a string is considered an option from the command line.
Parameters
arg string to be controlled
Returns
1 if it is an option, else 0
Definition at line 29 of file ctrlAndDoArgs.c.
{
     if (!(strncmp(arg, "--", 2) == 0)) {
         return 0;
     } else if (strncmp(arg, "--test", 6) == 0) {
         return 1;
     } else if (strncmp(arg, "--debug", 7) == 0) {
         return 1;
     } else if (strncmp(arg, "--doNothing", 11) == 0) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by doArg().
Variable Documentation
DEBUG
int DEBUG extern
Definition at line 2 of file main.c.
Referenced by doOption().