$P1$: /github/workspace/core/helperFunctions.c File Reference
helperFunctions.c File Reference
#include "sp1sLib.h"
Functions
int isTimeValid (tm time)
Controls that a time is valid in terms of minutes, hours, month number, year, month day.
int isTimeValid_min (int tm_min)
Controls that tm_min == [0, 59].
int isTimeValid_hour (int tm_hour)
Controls that tm_hour == [0, 23].
int isTimeValid_mon (int tm_mon)
Controls that tm_mon == [0, 11].
int isTimeValid_year (int tm_year)
Controls that tm_year > 1900.
int isTimeValid_mday (int tm_year, int tm_mon, int tm_mday)
Controls that a month day is valid depending on the year and month.
int daysInMonth (int tm_mon, int tm_year)
Calculates number of days in a month depending on the month and year.
int daysInMonthFeb (int tm_year)
Calculates the number of days in february on a given year.
int isLeapYear (int tm_year)
Controls is a year is a leap year.
void errorHandling (int statement, char errorMessage[])
If statement is true: print errorMessage and exit program returning EXIT_FAILURE.
void printCalendars (calendarSuite *calendarSuite)
Prints all data stored in calendarSuite.
void printMetadataCalendar (const calendar *calendar)
Prints all "readable" data in a calendar structure.
void printCalendar (const calendar *calendar)
Prints data stored in the linked list of eventLinks pointed to by calendar.
void printEvent (const event *a)
Prints all data from one single event structure.
void printMetadataCalendarSuite (calendarSuite calendarSuite)
Prints all data stored in calendar structs pointed to by calendarSuite.calPtrArray.
Variables
int DEBUG
Function Documentation
daysInMonth()
int daysInMonth (int tm_mon, int tm_year)
Calculates number of days in a month depending on the month and year.
Parameters
tm_mon month, january is month 0
tm_year year
Returns
number of days in month
Definition at line 109 of file helperFunctions.c.
{
     int returnValue;
     enum month { january,
                  february,
                  march,
                  april,
                  may,
                  june,
                  july,
                  august,
                  september,
                  october,
                  november,
                  december };
     switch (tm_mon) {
         case january:
         case march:
         case may:
         case july:
         case august:
         case october:
         case december:
             returnValue = 31;
             break;
         case april:
         case june:
         case september:
         case november:
             returnValue = 30;
             break;
         case february:
             returnValue = daysInMonthFeb(tm_year);
             break;
         default:
             returnValue = -1;
             break;
     }
     return returnValue;
 }
References daysInMonthFeb().
Referenced by isTimeValid_mday().
daysInMonthFeb()
int daysInMonthFeb (int tm_year)
Calculates the number of days in february on a given year.
Parameters
tm_year year
Returns
number of days in february
Definition at line 158 of file helperFunctions.c.
{
     if (isLeapYear(tm_year)) {
         return 29;
     } else {
         return 28;
     }
 }
References isLeapYear().
Referenced by daysInMonth().
errorHandling()
void errorHandling (int statement, char errorMessage[])
If statement is true: print errorMessage and exit program returning EXIT_FAILURE.
Parameters
statement Boolean expression.
errorMessage message to print if statement is true.
Definition at line 188 of file helperFunctions.c.
{
     if (statement) {
         printf("\n%s\n", errorMessage);
         exit(EXIT_FAILURE);
     }
 }
Referenced by findAvailableDates(), getCalendarSuite(), and mallocCalendarSuite().
isLeapYear()
int isLeapYear (int tm_year)
Controls is a year is a leap year.
Parameters
tm_year year
Returns
1 if the year is a leap year, else 0
Definition at line 172 of file helperFunctions.c.
{
     if (tm_year % 100 == 0 && tm_year % 400 != 0) {
         return 0;
     } else if (tm_year % 4 == 0) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by daysInMonthFeb().
isTimeValid()
int isTimeValid (tm time)
Controls that a time is valid in terms of minutes, hours, month number, year, month day.
The functions take leap years into account.
Parameters
time struct tm, from time.h, to be controlled
Returns
1 if time is valid, else 0
Definition at line 13 of file helperFunctions.c.
{
     int returnFlag = 0;
     returnFlag += isTimeValid_min(time.tm_min);
     returnFlag += isTimeValid_hour(time.tm_hour);
     returnFlag += isTimeValid_mon(time.tm_mon);
     returnFlag += isTimeValid_year(time.tm_year);
     returnFlag += isTimeValid_mday(time.tm_year, time.tm_mon, time.tm_mday);
     if (returnFlag == 5) {
         returnFlag = 1;
     } else {
         returnFlag = 0;
     }
     return returnFlag;
 }
References isTimeValid_hour(), isTimeValid_mday(), isTimeValid_min(), isTimeValid_mon(), and isTimeValid_year().
Referenced by getDates(), getLimits(), test10_isTimeValid(), test1_isTimeValid(), test2_isTimeValid(), test3_isTimeValid(), test4_isTimeValid(), test5_isTimeValid(), test6_isTimeValid(), test7_isTimeValid(), test8_isTimeValid(), and test9_isTimeValid().
isTimeValid_hour()
int isTimeValid_hour (int tm_hour)
Controls that tm_hour == [0, 23].
Parameters
tm_hour member of struct tm from time.h
Returns
1 if it’s within the boundary, else 0
Definition at line 50 of file helperFunctions.c.
{
     if (tm_hour >= 0 && tm_hour <= 23) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
isTimeValid_mday()
int isTimeValid_mday (int tm_year, int tm_mon, int tm_mday)
Controls that a month day is valid depending on the year and month.
Parameters
tm_year year
tm_mon month, january is month 0
tm_mday month day
Returns
1 if the month day is valid, else 0
Definition at line 94 of file helperFunctions.c.
{
     if (tm_mday <= daysInMonth(tm_mon, tm_year) && tm_mday > 0) {
         return 1;
     } else {
         return 0;
     }
 }
References daysInMonth().
Referenced by isTimeValid().
isTimeValid_min()
int isTimeValid_min (int tm_min)
Controls that tm_min == [0, 59].
Parameters
tm_min member of struct tm from time.h
Returns
1 if it’s within the boundary, else 0
Definition at line 36 of file helperFunctions.c.
{
     if (tm_min >= 0 && tm_min <= 59) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
isTimeValid_mon()
int isTimeValid_mon (int tm_mon)
Controls that tm_mon == [0, 11].
Parameters
tm_mon member of struct tm from time.h
Returns
1 if it’s within the boundary, else 0
Definition at line 64 of file helperFunctions.c.
{
     if (tm_mon >= 0 && tm_mon <= 11) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
isTimeValid_year()
int isTimeValid_year (int tm_year)
Controls that tm_year > 1900.
Parameters
tm_year member of struct tm from time.h
Returns
1 if it’s within the boundary, else 0
Definition at line 78 of file helperFunctions.c.
{
     if (tm_year >= 0) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
printCalendar()
void printCalendar (const calendar * calendar)
Prints data stored in the linked list of eventLinks pointed to by calendar.
Parameters
calendar Pointer to calendar from where the linked list should be printed.
Definition at line 224 of file helperFunctions.c.
{
     eventLink *cursor;
     int i = 1;
     cursor = calendar->firstEvent;
     printf("    EVENT: 0\n");
     printEvent(cursor->currentEvent);
     while (cursor->nextEventLink != NULL) {
         cursor = cursor->nextEventLink;
         printf("    EVENT: %d\n", i);
         printEvent(cursor->currentEvent);
         i++;
     }
     printf("Number of events: %d\n", calendar->numOfEvents);
 }
References eventLink::currentEvent, calendar::firstEvent, eventLink::nextEventLink, calendar::numOfEvents, and printEvent().
Referenced by printCalendars().
printCalendars()
void printCalendars (calendarSuite * calendarSuite)
Prints all data stored in calendarSuite.
Parameters
calendarSuite Suite to print.
Definition at line 200 of file helperFunctions.c.
{
     int i;
     for (i = 0; i < calendarSuite->Arraylen; i++) {
         printMetadataCalendar(calendarSuite->calPtrArray[i]);
         printCalendar(calendarSuite->calPtrArray[i]);
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, printCalendar(), and printMetadataCalendar().
Referenced by getCalendarSuite().
printEvent()
void printEvent (const event * a)
Prints all data from one single event structure.
Parameters
a Pointer to event structure.
Definition at line 247 of file helperFunctions.c.
{
     printf("    SUMMARY: %s\n", a->title);
     printf("    DTSTART: %.2d/%.2d/%.2d Time: %.2d:%.2d:%.2d\n",
            a->startTime.tm_year + 1900,
            a->startTime.tm_mon + 1,
            a->startTime.tm_mday,
            a->startTime.tm_hour,
            a->startTime.tm_min,
            a->startTime.tm_sec);
     printf("    DTEND:   %.2d/%.2d/%.2d Time: %.2d:%.2d:%.2d\n",
            a->endTime.tm_year + 1900,
            a->endTime.tm_mon + 1,
            a->endTime.tm_mday,
            a->endTime.tm_hour,
            a->endTime.tm_min,
            a->endTime.tm_sec);
     printf("    Priority: %d\n\n", a->priority);
 }
References event::endTime, event::priority, event::startTime, and event::title.
Referenced by printCalendar(), and printEventPtrArray().
printMetadataCalendar()
void printMetadataCalendar (const calendar * calendar)
Prints all "readable" data in a calendar structure.
Parameters
calendar Calendar structure to print.
Definition at line 213 of file helperFunctions.c.
{
     printf("calName: %s\n", calendar->calName);
     printf("fileName: %s\n", calendar->fileName);
     printf("numOfEvents: %d\n\n", calendar->numOfEvents);
 }
References calendar::calName, calendar::fileName, and calendar::numOfEvents.
Referenced by printCalendars(), and printMetadataCalendarSuite().
printMetadataCalendarSuite()
void printMetadataCalendarSuite (calendarSuite calendarSuite)
Prints all data stored in calendar structs pointed to by calendarSuite.calPtrArray.
Parameters
calendarSuite Suite from where the data should be printed from.
Definition at line 271 of file helperFunctions.c.
{
     int i;
     for (i = 0; i < calendarSuite.Arraylen; i++) {
         printf("\nCALENDAR %d: \n", i);
         printMetadataCalendar(calendarSuite.calPtrArray[i]);
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, and printMetadataCalendar().
Variable Documentation
DEBUG
int DEBUG extern
Definition at line 2 of file main.c.
Referenced by ctrlAndDoArgs(), findAvailableDates(), getCalendarSuite(), and getSearchParameters().