$P1$: /github/workspace/core/main.c File Reference
main.c File Reference
#include "sp1sLib.h"
Functions
int main (int argc, char *argv[])
This is where the magic happens 🤖
int ctrlAndDoArgs (int argc, char *argv[])
Controls and executes command-line arguments (only executes command-line options). If all arguments are not valid, terminates program with an error message.
void mallocCalendarSuite (int n, calendarSuite *calendarSuite)
Allocates memory for an calendarSuite.calPtrArray of length n.
void getSearchParameters (searchParameters *a)
Gets all of the search parameters and stores them in the struct. It also prints out the priority and length of the event.
void getCalendarSuite (int argc, char *argv[], calendarSuite *calendarSuite)
Based on a number of filepaths to *.ics files, builds an array of pointers to linked lists of calendar links/nodes and links/nodes data.
int findAvailableDates (calendarSuite *suite, const searchParameters *param, int searchMode)
As of now finds one time slot in suite, as defined by param and searchMode.
Variables
int DEBUG = 0
Function Documentation
ctrlAndDoArgs()
int ctrlAndDoArgs (int argc, char * argv[])
Controls and executes command-line arguments (only executes command-line options). If all arguments are not valid, terminates program with an error message.
All arguments are considered valid if they are either an *.ics file location or an option, and when there are more than two arguments.
Parameters
argc number of arguments
argv array of argument strings
Definition at line 40 of file main.c.
{
     int i = 1;
     int argsValid = argc >= 2;
     int icsFilesGot = 0;
     while (argsValid && i < argc) {
         argsValid = doArg(argv[i]);
         if (argsValid == icsFile) {
             icsFilesGot++;
         }
         i++;
     }
     if (DEBUG) {
         printf("argsValid = %d\nicsFilesGot = %d\n", argsValid, icsFilesGot);
     }
     if (!argsValid || icsFilesGot < 1) {
         exitWithError();
     }
     return icsFilesGot;
 }
References DEBUG, doArg(), exitWithError(), and icsFile.
Referenced by main().
findAvailableDates()
int findAvailableDates (calendarSuite * suite, const searchParameters * param, int searchMode)
As of now finds one time slot in suite, as defined by param and searchMode.
The sum of all events across the whole suite is found.
Space is allocated for an array of pointers to events(allEvents), the lenght of this array is equal to the sum of all events across the whole suite.
The allEvents array is then filled with pointers to all events in suite. If searchMode == byRestructuring, events with a higher priority than param->priority are ignored.
The allEvents array is sorted by endTime in ascending order.
The functions tries to find one avalible date, and prints the result of the search on screen.
Parameters
suite A pointer to a calendarSuite for the program to find a date in.
param A struct of search paramerters
searchMode Used to check if priority of param is used, or using default value
Returns
int Bool value telling if a possible date for event was found.
Definition at line 160 of file main.c.
{
     int foundDate = 0, sumAllEvents = 0;
     event **allEvents;
     tm freeSlot;
     /* -1- */
     sumAllEvents = findSumAllEvents(suite);
     if (DEBUG) {
         printf("\nsumAllEvents: %d", sumAllEvents);
     }
     /* -2- */
     allEvents = (event **)malloc(sumAllEvents * sizeof(event *));
     errorHandling(allEvents == NULL, "!!!FAILED TO ALLOCATE MEMORY STEP 3!!!");
     /* -3- */
     if (searchMode == bylooking) {
         calSuiteToEventArray(suite, sumAllEvents, MAX_PRIORITY, allEvents); /* <------ This should be account for elsewhere*/
     } else if (searchMode == byRestructuring) {
         calSuiteToEventArray(suite, sumAllEvents, param->priority, allEvents);
     }
     if (DEBUG) {
         printf("\nEVENT ARRAY:\n");
         printEventPtrArray(allEvents, sumAllEvents);
     }
     /* -4- */
     qsort(allEvents, sumAllEvents, sizeof(event *), endTimeCmp); /* Sorting array of events in chronological order by endTime */
     if (DEBUG) {
         printf("\nSORTED EVENT ARRAY:\n");
         printEventPtrArray(allEvents, sumAllEvents);
     }
     /* -5- */
     freeSlot = lookForFreeSlot(param, sumAllEvents, allEvents);
     if(freeSlot.tm_year >= 0) {
         printf("Free slot found at: %.2d/%.2d/%.4d %.2d:%.2d\n",
                 freeSlot.tm_mday,
                 freeSlot.tm_mon + 1,
                 freeSlot.tm_year + EPOCH,
                 freeSlot.tm_hour,
                 freeSlot.tm_min);
         foundDate = 1;
     } else {
         printf("Found no date :(\n");
     }
     free(allEvents);
     return foundDate;
 }
References bylooking, byRestructuring, calSuiteToEventArray(), DEBUG, endTimeCmp(), EPOCH, errorHandling(), findSumAllEvents(), lookForFreeSlot(), MAX_PRIORITY, printEventPtrArray(), and searchParameters::priority.
Referenced by main().
getCalendarSuite()
void getCalendarSuite (int argc, char * argv[], calendarSuite * calendarSuite)
Based on a number of filepaths to *.ics files, builds an array of pointers to linked lists of calendar links/nodes and links/nodes data.
Each linked list correspondes to each *.ics file gotten. Each linked list starts with a node/link struct called calendar, this struct is documented in sp1sLib.h. After this the linked list is made of node/link structs called eventLink, these contain data for one event each, they are also documented in sp1sLib.h.
The function looks through argc amount of arguments, argv, not all argumets need to be *.ics file paths, but all *.ics filepaths have to be valid, if this is not the case function terminates program with an error message.
Parameters
argc number of arguments
argv arguments
[in,out] calendarSuite
Warning
This function does not control the validity of the data gotten from the *.ics files. [errorHandling(!returnFlag, "!!!ERROR IN *.ICS FILE!!!");] does nothing at the moment.
Definition at line 128 of file main.c.
{
     int returnFlag = 0;
     returnFlag = getCalendarSuiteGetFile(argc, argv, calendarSuite->calPtrArray);
     errorHandling(!returnFlag, "!!!INVALID FILE LOCATION!!!");
     returnFlag = getCalendarSuiteGetData(calendarSuite);
     errorHandling(!returnFlag, "!!!ERROR IN *.ICS FILE!!!");
     if (DEBUG) {
         printf("\nICS FILE DATA GOT:\n\n");
         printCalendars(calendarSuite);
     }
 }
References calendarSuite::calPtrArray, DEBUG, errorHandling(), getCalendarSuiteGetData(), getCalendarSuiteGetFile(), and printCalendars().
Referenced by main().
getSearchParameters()
void getSearchParameters (searchParameters * a)
Gets all of the search parameters and stores them in the struct. It also prints out the priority and length of the event.
Parameters
a
Definition at line 95 of file main.c.
{
     a->priority = getPriority();
     a->eventLen = getEventLen();
     a->buffer  = getEventBuffer();
     getDates(&a->startDate, &a->endDate);
     getLimits(&a->lowerLimit, &a->upperLimit);
     if (DEBUG) {
         printf("Priority: %d\nEventLen: %d", a->priority, a->eventLen);
     }
 }
References searchParameters::buffer, DEBUG, searchParameters::endDate, searchParameters::eventLen, getDates(), getEventBuffer(), getEventLen(), getLimits(), getPriority(), searchParameters::lowerLimit, searchParameters::priority, searchParameters::startDate, and searchParameters::upperLimit.
Referenced by main().
main()
int main (int argc, char * argv[])
This is where the magic happens 🤖
Parameters
argc Amount of arguments provided as a command line input including the program itself
argv An array of all command line arguments including the program itself
Returns
int The exit code of the program
Definition at line 11 of file main.c.
{
     int foundDatesByLooking = 0;
     searchParameters searchParametersMain;
     calendarSuite calendarSuiteMain;
     mallocCalendarSuite(ctrlAndDoArgs(argc, argv), &calendarSuiteMain);
     getCalendarSuite(argc, argv, &calendarSuiteMain);
     getSearchParameters(&searchParametersMain);
     foundDatesByLooking = findAvailableDates(&calendarSuiteMain, &searchParametersMain, bylooking);
     if (!foundDatesByLooking) {
         findAvailableDates(&calendarSuiteMain, &searchParametersMain, byRestructuring);
     }
     return EXIT_SUCCESS;
 }
References bylooking, byRestructuring, ctrlAndDoArgs(), findAvailableDates(), getCalendarSuite(), getSearchParameters(), and mallocCalendarSuite().
mallocCalendarSuite()
void mallocCalendarSuite (int n, calendarSuite * calendarSuite)
Allocates memory for an calendarSuite.calPtrArray of length n.
Terminates the program if it fails to allocate memory.
Parameters
n length of array
calendarSuite output parameter, calendarSuite to be allocated memory
Definition at line 72 of file main.c.
{
     int i = 0;
     calendarSuite->Arraylen = n;
     calendarSuite->calPtrArray = (calendar **)malloc((n) * sizeof(calendar *));
     errorHandling(calendarSuite->calPtrArray == NULL, "!!!FAILED TO ALLOCATE MEMORY STEP 1!!!");
     while (i < n) {
         calendarSuite->calPtrArray[i] = (calendar *)malloc(sizeof(calendar));
         calendarSuite->calPtrArray[i]->firstEvent = NULL;
         errorHandling(calendarSuite->calPtrArray[i] == NULL, "!!!FAILED TO ALLOCATE MEMORY STEP 2!!!");
         i++;
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, errorHandling(), and calendar::firstEvent.
Referenced by main(), test1_getCalendarSuiteGetFile(), and test2_getCalendarSuiteGetFile().
Variable Documentation
DEBUG
int DEBUG = 0
Definition at line 2 of file main.c.
Referenced by ctrlAndDoArgs(), doOption(), findAvailableDates(), getCalendarSuite(), getDates(), getLimits(), getSearchParameters(), lookForFreeSlot(), lookForFreeSlotSingle(), and stuckProcedure().