$P1$: /github/workspace/core/sp1sLib.h File Reference
sp1sLib.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "CuTest.h"
Data Structures
struct event
Struct for holding event information.
struct eventLink
Struct for a linked list of event structs.
struct calendar
Head of linked list of eventLinks.
struct searchParameters
Struct for search parameters used to scope the search of available dates in calendar-lists.
struct calendarSuite
struct for containing an array of pointer to calendar-lists.
Macros
#define LINE_LEN 512
#define DO_NOTHING 0
#define MIN_TO_SEC 60
#define EPOCH 1900
#define MAX_PRIORITY 1000
#define UNIX_24H 60 * 60 * 24;
#define INIT_TM { 0, 0, 0, 1, 0, 0, 0, 0, -1 }
Typedefs
typedef struct tm tm
typedef struct event event
Struct for holding event information.
typedef struct eventLink eventLink
Struct for a linked list of event structs.
typedef struct calendar calendar
Head of linked list of eventLinks.
typedef struct searchParameters searchParameters
Struct for search parameters used to scope the search of available dates in calendar-lists.
typedef struct calendarSuite calendarSuite
struct for containing an array of pointer to calendar-lists.
Enumerations
enum argType { invalid, icsFile, option }
enum searchMode { bylooking, byRestructuring }
enum lookForFreeSlotStatus { eol = -1, look = -2, redo = -3 }
Functions
int ctrlAndDoArgs (int argc, char *argv[])
Controls and executes command-line arguments (only executes command-line options). If all arguments are not valid, terminates program with an error message.
void mallocCalendarSuite (int n, calendarSuite *calendarSuite)
Allocates memory for an calendarSuite.calPtrArray of length n.
int doArg (char arg[])
Controls what a command line argument is considered, and executes options if command line argument is an option.
int isIcsFile (char arg[])
Controls that a string ends with ".ics".
int isOption (char arg[])
Controls if a string is considered an option from the command line.
void doOption (char arg[])
Executes an option.
void exitWithError (void)
Displays error message and terminates the program.
void getSearchParameters (searchParameters *a)
int getPriority (void)
Get the Priority object.
int getEventLen (void)
Get the Event Len object.
int getEventBuffer (void)
Prompts user: Enter how much buffer time should be in beginning and end of event.
void getDates (tm *startDate, tm *endDate)
Get the Dates object.
void getLimits (tm *lowerLimmit, tm *upperLimit)
Get the Limits object.
void getCalendarSuite (int argc, char *argv[], calendarSuite *calendarSuite)
Based on a number of filepaths to *.ics files, builds an array of pointers to linked lists of calendar links/nodes and links/nodes data.
int getCalendarSuiteGetFile (int argc, char *argv[], calendar *calendarSuite[])
Opens and stores file-pointer / file-path in calPtrArray.
int getCalendarSuiteGetFileSingle (char arg[], calendar *calendar)
Tries to open arg as a file, stores the file-path and file-pointer in calendar.
int getCalendarSuiteGetData (calendarSuite *calendarSuite)
Builds a linked list of eventLinks, for each calendar pointed to by calendarSuite.calPtrArray.
int getCalendarSuiteGetDataSingle (calendar *calendar)
Builds a linked list from data pointed to by the FILE pointer file contained in calendar, makes calendar.firstEvent point to the first link/nodes in this linked list of eventLink.
void addEventCal (event *newEvent, calendar *calendar)
Adds an eventLink pointing to newEvent to the end of the linked list that is inputCal.
eventLink * mallocEventLink (event *eventP, eventLink *eventLinkP)
Creates a new eventLink.
int findAvailableDates (calendarSuite *suite, const searchParameters *param, int searchMode)
As of now finds one time slot in suite, as defined by param and searchMode.
int findSumAllEvents (const calendarSuite *suite)
Finds the sum of all events in a given calendarSuite.
void calSuiteToEventArray (const calendarSuite *suite, int sumAllEvents, int priority, event *eventPtrArray[])
Iterates through all events from all calendar-files and adds them all to one big array.
int endTimeCmp (const void *arg1, const void *arg2)
Compares two events to determine which event ends the latest.
int eventStartsLater (const event *event1, const event *event2)
Determines if event1 ends later than event2.
tm lookForFreeSlot (const searchParameters *p, int arrLen, event *allEvents[])
Looks for a free time slot, defined by p, in a sorted array of pointers to events.
tm lookForFreeSlotSingle (const searchParameters *p, event *event, time_t *head)
Looks for a free time slot between head and event->startTime.
int endOfLine (const searchParameters *p, time_t head)
Controls that head has not gone over the final time, called endOfLine, where an event could be found as defined by p.
int canElongate (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head, const searchParameters *p)
Controls if head is considered able to elongate over event.
int canSwallow (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head)
Controls if head is considered able to swallow event.
int stuck (time_t eventStartTimeUnix, time_t head, const searchParameters *p)
Controls if head is considered stuck.
tm stuckProcedure (const searchParameters *p, time_t *head)
Runs the procedure corresponding to when head is considered stuck.
int headWithinLimits (const searchParameters *p, time_t head)
Controls that an event that starts at head, and is defined by p is within limits.
int tmWithinLimits (const searchParameters *p, const tm *time)
Controls that time is within lowerLimit and upperLimit defined in p.
void setHeadToNextLL (const searchParameters *p, time_t *head)
Sets head to be the next lowerLimit.
int overUpperLimit (const searchParameters *p, const tm *head_tm)
Controls if head_tm is over upperLimit.
int underLowerLimit (const searchParameters *p, const tm *head_tm)
Controls if head_tm is under lowerLimit.
void goToLowerLimitNextDay (time_t head, const searchParameters *p, tm *head_tm)
Sets head_tm to lowerLimit the next day.
void goToLowerLimitThisDay (const searchParameters *p, tm *head_tm)
Sets head_tm to lowerLimit same day.
time_t getStartOfLine (const searchParameters *p)
Finds the earliest time an event can take place, according to p.
time_t getEndOfLine (const searchParameters *p)
Finds the latest time an event can take place, according to p.
void print_time_t (time_t time)
Converts a time_t to a tm structure, prints the tm structure.
int isTimeValid (tm time)
Controls that a time is valid in terms of minutes, hours, month number, year, month day.
int isTimeValid_min (int tm_min)
Controls that tm_min == [0, 59].
int isTimeValid_hour (int tm_hour)
Controls that tm_hour == [0, 23].
int isTimeValid_mon (int tm_mon)
Controls that tm_mon == [0, 11].
int isTimeValid_year (int tm_year)
Controls that tm_year > 1900.
int isTimeValid_mday (int tm_year, int tm_mon, int tm_mday)
Controls that a month day is valid depending on the year and month.
int daysInMonth (int tm_mon, int tm_year)
Calculates number of days in a month depending on the month and year.
int daysInMonthFeb (int tm_year)
Calculates the number of days in february on a given year.
int isLeapYear (int tm_year)
Controls is a year is a leap year.
void errorHandling (int statement, char ErrorMessage[])
If statement is true: print errorMessage and exit program returning EXIT_FAILURE.
void printMetadataCalendarSuite (calendarSuite calendarSuite)
Prints all data stored in calendar structs pointed to by calendarSuite.calPtrArray.
void printMetadataCalendar (const calendar *calendar)
Prints all "readable" data in a calendar structure.
void printCalendar (const calendar *calendar)
Prints data stored in the linked list of eventLinks pointed to by calendar.
void printCalendars (calendarSuite *calendarSuite)
Prints all data stored in calendarSuite.
void printEvent (const event *a)
Prints all data from one single event structure.
void printEventPtrArray (event *allEvents[], int n)
Prints all event data in a given array of pointer to events of length n.
void test1_doArg (CuTest *tc)
void test2_doArg (CuTest *tc)
void test3_doArg (CuTest *tc)
CuSuite * suite_ctrlAndDoArgs (void)
void test1_getCalendarSuiteGetFile (CuTest *tc)
void test2_getCalendarSuiteGetFile (CuTest *tc)
void test1_getCalendarSuiteGetFileSingle (CuTest *tc)
void test2_getCalendarSuiteGetFileSingle (CuTest *tc)
CuSuite * suite_getCalendarSuite (void)
void test1_isTimeValid (CuTest *tc)
void test2_isTimeValid (CuTest *tc)
void test3_isTimeValid (CuTest *tc)
void test4_isTimeValid (CuTest *tc)
void test5_isTimeValid (CuTest *tc)
void test6_isTimeValid (CuTest *tc)
void test7_isTimeValid (CuTest *tc)
void test8_isTimeValid (CuTest *tc)
void test9_isTimeValid (CuTest *tc)
void test10_isTimeValid (CuTest *tc)
CuSuite * suite_sharedFunctions (void)
void runAllTests (void)
Macro Definition Documentation
DO_NOTHING
#define DO_NOTHING 0
Definition at line 11 of file sp1sLib.h.
EPOCH
#define EPOCH 1900
Definition at line 13 of file sp1sLib.h.
INIT_TM
#define INIT_TM { 0, 0, 0, 1, 0, 0, 0, 0, -1 }
Definition at line 17 of file sp1sLib.h.
LINE_LEN
#define LINE_LEN 512
Definition at line 10 of file sp1sLib.h.
MAX_PRIORITY
#define MAX_PRIORITY 1000
Definition at line 14 of file sp1sLib.h.
MIN_TO_SEC
#define MIN_TO_SEC 60
Definition at line 12 of file sp1sLib.h.
UNIX_24H
#define UNIX_24H 60 * 60 * 24;
Definition at line 16 of file sp1sLib.h.
Typedef Documentation
calendar
typedef struct calendar calendar
Head of linked list of eventLinks.
contains metadata about the events in the eventLinks, a linked list like this is called a calendar-list. Events form the same calendar are supposed to be stored in the same calendar-list
calendarSuite
typedef struct calendarSuite calendarSuite
struct for containing an array of pointer to calendar-lists.
ArrayLen is the length of calPtrArray
event
typedef struct event event
Struct for holding event information.
eventLink
typedef struct eventLink eventLink
Struct for a linked list of event structs.
searchParameters
typedef struct searchParameters searchParameters
Struct for search parameters used to scope the search of available dates in calendar-lists.
tm
typedef struct tm tm
Definition at line 1 of file sp1sLib.h.
Enumeration Type Documentation
argType
enum argType
Enumerator
invalid
icsFile
option
Definition at line 84 of file sp1sLib.h.
              { invalid,
                icsFile,
                option };
lookForFreeSlotStatus
enum lookForFreeSlotStatus
Enumerator
eol
look
redo
Definition at line 91 of file sp1sLib.h.
                            { eol = -1, /* endOfLine */
                              look = -2,
                              redo = -3 };
searchMode
enum searchMode
Enumerator
bylooking
byRestructuring
Definition at line 88 of file sp1sLib.h.
                 { bylooking,
                   byRestructuring };
Function Documentation
addEventCal()
void addEventCal (event * newEvent, calendar * inputCal)
Adds an eventLink pointing to newEvent to the end of the linked list that is inputCal.
Allocates space for the new eventLink, then goes to the bottom of the linked list inputCal and points the NULL pointer to the new eventLink.
Parameters
newEvent The new event to be added at the end of the linked list.
inputCal First element in the linked list where newEvent needs to be added.
Definition at line 162 of file getCalendarSuite.c.
{
     eventLink *cursor, *newLink;
     newLink = mallocEventLink(newEvent, NULL);
     if (inputCal->firstEvent == NULL) {
         inputCal->firstEvent = newLink;
     } else {
         cursor = inputCal->firstEvent;
         while (cursor->nextEventLink != NULL) {
             cursor = cursor->nextEventLink;
         }
         cursor->nextEventLink = newLink;
     }
 }
References calendar::firstEvent, mallocEventLink(), and eventLink::nextEventLink.
Referenced by getCalendarSuiteGetDataSingle().
calSuiteToEventArray()
void calSuiteToEventArray (const calendarSuite * suite, int sumAllEvents, int priority, event * eventPtrArray[])
Iterates through all events from all calendar-files and adds them all to one big array.
The function loops through all calendars and adds all the events to one array. An event will only be added to the array if it has priority over the event we are finding an avaliable slot for.
Parameters
suite the suite of calendars to look through
eventPtrArray The array to put all events into
sumAllEvents The amount of events across all calendar files
priority The priority of the event the user wants to find an avaliable time slot for. Defaults to 1000
Definition at line 37 of file findAvailableDates.c.
{
     int i = 0, k;
     eventLink *cursor;
     for (k = 0; k < suite->Arraylen; k++) {
         cursor = suite->calPtrArray[k]->firstEvent;
         while (cursor != NULL) {
             if (cursor->currentEvent->priority <= priority) {
                 eventPtrArray[i] = cursor->currentEvent;
             } else {
                 eventPtrArray[i] = NULL;
             }
             cursor = cursor->nextEventLink;
             i++;
         }
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, eventLink::currentEvent, calendar::firstEvent, eventLink::nextEventLink, and event::priority.
Referenced by findAvailableDates().
canElongate()
int canElongate (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head, const searchParameters * p)
Controls if head is considered able to elongate over event.
Head is considered able to elongate if:
head is smaller than eventEndTimeUnix and head is larger than or equal to eventStartTimeUnix
head is smaller than eventStartTimeUnix, and the time between head and eventStartTimeUnix is smaller than: eventLen + buffer * 2 (unix time)
Parameters
eventStartTimeUnix Start of event in unix time.
eventEndTimeUnix End of event in unix time.
head Head to control.
p Search parameters, where eventLen and buffer are contained.
Returns
1 if it is able to elongate, else 0.
Precondition
MIN_TO_SEC should be #defined as 60.
Definition at line 251 of file findAvailableDates.c.
{
     return ((head < eventEndTimeUnix) && (head >= eventStartTimeUnix)) ||
            ((head < eventStartTimeUnix) && ((eventStartTimeUnix - head) < ((p->eventLen * MIN_TO_SEC) + (2 * p->buffer * MIN_TO_SEC))));
 }
References searchParameters::buffer, searchParameters::eventLen, and MIN_TO_SEC.
Referenced by lookForFreeSlotSingle().
canSwallow()
int canSwallow (time_t eventStartTimeUnix, time_t eventEndTimeUnix, time_t head)
Controls if head is considered able to swallow event.
Head is considered able to swallow event if: head is larger than both eventStartTimeUnix and eventEndTimeUnix.
Parameters
eventStartTimeUnix Start of event in unix time.
eventEndTimeUnix End of event in unix time.
head Head to control.
Returns
1 if head is able to swallow, else 0.
Definition at line 267 of file findAvailableDates.c.
{
     return (head > eventEndTimeUnix) && (head > eventStartTimeUnix);
 }
Referenced by lookForFreeSlotSingle().
ctrlAndDoArgs()
int ctrlAndDoArgs (int argc, char * argv[])
Controls and executes command-line arguments (only executes command-line options). If all arguments are not valid, terminates program with an error message.
All arguments are considered valid if they are either an *.ics file location or an option, and when there are more than two arguments.
Parameters
argc number of arguments
argv array of argument strings
Definition at line 40 of file main.c.
{
     int i = 1;
     int argsValid = argc >= 2;
     int icsFilesGot = 0;
     while (argsValid && i < argc) {
         argsValid = doArg(argv[i]);
         if (argsValid == icsFile) {
             icsFilesGot++;
         }
         i++;
     }
     if (DEBUG) {
         printf("argsValid = %d\nicsFilesGot = %d\n", argsValid, icsFilesGot);
     }
     if (!argsValid || icsFilesGot < 1) {
         exitWithError();
     }
     return icsFilesGot;
 }
References DEBUG, doArg(), exitWithError(), and icsFile.
Referenced by main().
daysInMonth()
int daysInMonth (int tm_mon, int tm_year)
Calculates number of days in a month depending on the month and year.
Parameters
tm_mon month, january is month 0
tm_year year
Returns
number of days in month
Definition at line 109 of file helperFunctions.c.
{
     int returnValue;
     enum month { january,
                  february,
                  march,
                  april,
                  may,
                  june,
                  july,
                  august,
                  september,
                  october,
                  november,
                  december };
     switch (tm_mon) {
         case january:
         case march:
         case may:
         case july:
         case august:
         case october:
         case december:
             returnValue = 31;
             break;
         case april:
         case june:
         case september:
         case november:
             returnValue = 30;
             break;
         case february:
             returnValue = daysInMonthFeb(tm_year);
             break;
         default:
             returnValue = -1;
             break;
     }
     return returnValue;
 }
References daysInMonthFeb().
Referenced by isTimeValid_mday().
daysInMonthFeb()
int daysInMonthFeb (int tm_year)
Calculates the number of days in february on a given year.
Parameters
tm_year year
Returns
number of days in february
Definition at line 158 of file helperFunctions.c.
{
     if (isLeapYear(tm_year)) {
         return 29;
     } else {
         return 28;
     }
 }
References isLeapYear().
Referenced by daysInMonth().
doArg()
int doArg (char arg[])
Controls what a command line argument is considered, and executes options if command line argument is an option.
Parameters
arg argument to be controlled
Returns
enum icsFile if the argument is an *.ics file, enum option if the argument is an option, else enum invalid.
Definition at line 12 of file ctrlAndDoArgs.c.
                       {
     if (isIcsFile(arg)) {
         return icsFile;
     } else if (isOption(arg)) {
         doOption(arg);
         return option;
     } else {
         return invalid;
     }
 }
References doOption(), icsFile, invalid, isIcsFile(), isOption(), and option.
Referenced by ctrlAndDoArgs(), test1_doArg(), test2_doArg(), and test3_doArg().
doOption()
void doOption (char arg[])
Executes an option.
Parameters
arg string of option to be executed
Definition at line 62 of file ctrlAndDoArgs.c.
{
     if (strncmp(arg, "--test", 6) == 0) {
         runAllTests();
         exit(EXIT_SUCCESS);
     } else if (strncmp(arg, "--debug", 7) == 0) {
         DEBUG = 1;
     } else if (strncmp(arg, "--doNothing", 11) == 0) {
         /* do nothing */
     }
 }
References DEBUG, and runAllTests().
Referenced by doArg().
endOfLine()
int endOfLine (const searchParameters * p, time_t head)
Controls that head has not gone over the final time, called endOfLine, where an event could be found as defined by p.
endOfLine is given by getEndOfLine().
Parameters
p Search parameters, where endOfLine can be found.
head time_t to control.
Returns
1 if head is a or over endOfLine.
Definition at line 230 of file findAvailableDates.c.
{
     time_t eolTime = getEndOfLine(p);
     return head >= eolTime;
 }
References getEndOfLine().
Referenced by lookForFreeSlotSingle().
endTimeCmp()
int endTimeCmp (const void * arg1, const void * arg2)
Compares two events to determine which event ends the latest.
Parameters
arg1 first event to be compared
arg2 second event to be compared
Returns
1 if the first event ends before the second, -1 if the second event ends before the first, 0 if both events end at the same time.
Definition at line 64 of file findAvailableDates.c.
{
     event **event1 = (event **)arg1;
     event **event2 = (event **)arg2;
     if (*event1 == NULL && *event2 != NULL) {
         return 1;
     } else if (*event1 != NULL && *event2 == NULL) {
         return -1;
     } else if (*event1 == NULL && *event2 == NULL) {
         return 0;
     } else if (eventStartsLater(*event1, *event2)) {
         return 1;
     } else if (eventStartsLater(*event2, *event1)) {
         return -1;
     } else {
         return 0;
     }
 }
References eventStartsLater().
Referenced by findAvailableDates().
errorHandling()
void errorHandling (int statement, char errorMessage[])
If statement is true: print errorMessage and exit program returning EXIT_FAILURE.
Parameters
statement Boolean expression.
errorMessage message to print if statement is true.
Definition at line 188 of file helperFunctions.c.
{
     if (statement) {
         printf("\n%s\n", errorMessage);
         exit(EXIT_FAILURE);
     }
 }
Referenced by findAvailableDates(), getCalendarSuite(), and mallocCalendarSuite().
eventStartsLater()
int eventStartsLater (const event * event1, const event * event2)
Determines if event1 ends later than event2.
Parameters
event1 pointer to event structure
event2 pointer to event structure
Returns
int 1 if event1 ends later than event 2, 0 if event 2 ends later than event1 or they end at the same time
Definition at line 91 of file findAvailableDates.c.
{
     if (event1->startTime.tm_year > event2->startTime.tm_year) { /* Check year */
         return 1;
     } else if (event1->startTime.tm_year < event2->startTime.tm_year) {
         return 0;
     } else if (event1->startTime.tm_mon > event2->startTime.tm_mon) { /* Check month */
         return 1;
     } else if (event1->startTime.tm_year < event2->startTime.tm_year) {
         return 0;
     } else if (event1->startTime.tm_mday > event2->startTime.tm_mday) { /* Check day */
         return 1;
     } else if (event1->startTime.tm_mday < event2->startTime.tm_mday) {
         return 0;
     } else if (event1->startTime.tm_hour > event2->startTime.tm_hour) { /* Check hour */
         return 1;
     } else if (event1->startTime.tm_hour < event2->startTime.tm_hour) {
         return 0;
     } else if (event1->startTime.tm_min > event2->startTime.tm_min) { /* Check min */
         return 1;
     } else if (event1->startTime.tm_min < event2->startTime.tm_min) {
         return 0;
     } else if (event1->startTime.tm_sec > event2->startTime.tm_sec) { /* Check secs */
         return 1;
     } else {
         return 0;
     }
 }
References event::startTime.
Referenced by endTimeCmp().
exitWithError()
void exitWithError (void)
Displays error message and terminates the program.
Definition at line 76 of file ctrlAndDoArgs.c.
{
     printf("Invalid argument, Please provide one or more .ics files\n");
     exit(EXIT_FAILURE);
 }
Referenced by ctrlAndDoArgs().
findAvailableDates()
int findAvailableDates (calendarSuite * suite, const searchParameters * param, int searchMode)
As of now finds one time slot in suite, as defined by param and searchMode.
The sum of all events across the whole suite is found.
Space is allocated for an array of pointers to events(allEvents), the lenght of this array is equal to the sum of all events across the whole suite.
The allEvents array is then filled with pointers to all events in suite. If searchMode == byRestructuring, events with a higher priority than param->priority are ignored.
The allEvents array is sorted by endTime in ascending order.
The functions tries to find one avalible date, and prints the result of the search on screen.
Parameters
suite A pointer to a calendarSuite for the program to find a date in.
param A struct of search paramerters
searchMode Used to check if priority of param is used, or using default value
Returns
int Bool value telling if a possible date for event was found.
Definition at line 157 of file main.c.
{
     int foundDate = 0, sumAllEvents = 0;
     event **allEvents;
     tm freeSlot;
     /* -1- */
     sumAllEvents = findSumAllEvents(suite);
     if (DEBUG) {
         printf("\nsumAllEvents: %d", sumAllEvents);
     }
     /* -2- */
     allEvents = (event **)malloc(sumAllEvents * sizeof(event *));
     errorHandling(allEvents == NULL, "!!!FAILED TO ALLOCATE MEMORY STEP 3!!!");
     /* -3- */
     if (searchMode == bylooking) {
         calSuiteToEventArray(suite, sumAllEvents, MAX_PRIORITY, allEvents); /* <------ This should be account for elsewhere*/
     } else if (searchMode == byRestructuring) {
         calSuiteToEventArray(suite, sumAllEvents, param->priority, allEvents);
     }
     if (DEBUG) {
         printf("\nEVENT ARRAY:\n");
         printEventPtrArray(allEvents, sumAllEvents);
     }
     /* -4- */
     qsort(allEvents, sumAllEvents, sizeof(event *), endTimeCmp); /* Sorting array of events in chronological order by endTime */
     if (DEBUG) {
         printf("\nSORTED EVENT ARRAY:\n");
         printEventPtrArray(allEvents, sumAllEvents);
     }
     /* -5- */
     freeSlot = lookForFreeSlot(param, sumAllEvents, allEvents);
     if(freeSlot.tm_year >= 0) {
         printf("Free slot found at: %.2d/%.2d/%.4d %.2d:%.2d\n",
                 freeSlot.tm_mday,
                 freeSlot.tm_mon + 1,
                 freeSlot.tm_year + EPOCH,
                 freeSlot.tm_hour,
                 freeSlot.tm_min);
         foundDate = 1;
     } else {
         printf("Found no date :(\n");
     }
     free(allEvents);
     return foundDate;
 }
References bylooking, byRestructuring, calSuiteToEventArray(), DEBUG, endTimeCmp(), EPOCH, errorHandling(), findSumAllEvents(), lookForFreeSlot(), MAX_PRIORITY, printEventPtrArray(), and searchParameters::priority.
Referenced by main().
findSumAllEvents()
int findSumAllEvents (const calendarSuite * suite)
Finds the sum of all events in a given calendarSuite.
The sum is found by adding up all the sums found in suite->calPtrArray[i]->numOfEvents.
Parameters
suite calendarSuite where sum of all events should be found
Returns
sum of all events in calendarSuite
Definition at line 12 of file findAvailableDates.c.
{
     int i = 0, sum = 0;
     while (i < suite->Arraylen) {
         sum += suite->calPtrArray[i]->numOfEvents;
         i++;
     }
     return sum;
 }
References calendarSuite::calPtrArray, and calendar::numOfEvents.
Referenced by findAvailableDates().
getCalendarSuite()
void getCalendarSuite (int argc, char * argv[], calendarSuite * calendarSuite)
Based on a number of filepaths to *.ics files, builds an array of pointers to linked lists of calendar links/nodes and links/nodes data.
Each linked list correspondes to each *.ics file gotten. Each linked list starts with a node/link struct called calendar, this struct is documented in sp1sLib.h. After this the linked list is made of node/link structs called eventLink, these contain data for one event each, they are also documented in sp1sLib.h.
The function looks through argc amount of arguments, argv, not all argumets need to be *.ics file paths, but all *.ics filepaths have to be valid, if this is not the case function terminates program with an error message.
Parameters
argc number of arguments
argv arguments
[in,out] calendarSuite
Warning
This function does not control the validity of the data gotten from the *.ics files. [errorHandling(!returnFlag, "!!!ERROR IN *.ICS FILE!!!");] does nothing at the moment.
Definition at line 125 of file main.c.
{
     int returnFlag = 0;
     returnFlag = getCalendarSuiteGetFile(argc, argv, calendarSuite->calPtrArray);
     errorHandling(!returnFlag, "!!!INVALID FILE LOCATION!!!");
     returnFlag = getCalendarSuiteGetData(calendarSuite);
     errorHandling(!returnFlag, "!!!ERROR IN *.ICS FILE!!!");
     if (DEBUG) {
         printf("\nICS FILE DATA GOT:\n\n");
         printCalendars(calendarSuite);
     }
 }
References calendarSuite::calPtrArray, DEBUG, errorHandling(), getCalendarSuiteGetData(), getCalendarSuiteGetFile(), and printCalendars().
Referenced by main().
getCalendarSuiteGetData()
int getCalendarSuiteGetData (calendarSuite * calendarSuite)
Builds a linked list of eventLinks, for each calendar pointed to by calendarSuite.calPtrArray.
This functions will also fclose the filepointer stored in each calendarSuite, when it has read the data it needs.
Parameters
calendarSuite Suite of calendars from where the linked lists should be build.
Returns
Returns 1 if no error is found i files, else 0 (this is not implemented at the moment).
Definition at line 62 of file getCalendarSuite.c.
{
     int i = 0, errorFlag = 1;
     while (i < calendarSuite->Arraylen && errorFlag) {
         errorFlag = getCalendarSuiteGetDataSingle(calendarSuite->calPtrArray[i]);
         fclose(calendarSuite->calPtrArray[i]->file);
         i++;
     }
     return errorFlag;
 }
References calendarSuite::calPtrArray, calendar::file, and getCalendarSuiteGetDataSingle().
Referenced by getCalendarSuite().
getCalendarSuiteGetDataSingle()
int getCalendarSuiteGetDataSingle (calendar * calendar)
Builds a linked list from data pointed to by the FILE pointer file contained in calendar, makes calendar.firstEvent point to the first link/nodes in this linked list of eventLink.
This functions scans through the file pointed to by the FILE pointer contained in calendar. For each events the functions reads allocates space for this data in the heap, and points to this data in the linked list that is created. The number of events in each calendar is calculated and stored in calendar.numOfEvents.
Parameters
calendar Calendar from where the linked list should be build from.
Returns
1.
Definition at line 87 of file getCalendarSuite.c.
{
     event *newEvent;
     int isEvent = 0, numOfEvents = 0;
     char line[LINE_LEN], leftOverGarbage[LINE_LEN];
     while (fgets(line, LINE_LEN, calendar->file)) {
         if (strstr(line, "BEGIN:VEVENT")) { /* Find linjer hvor et event starter */
             isEvent = 1;
             numOfEvents++;
             newEvent = (event *)malloc(sizeof(event));
         }
         if (isEvent) {
             int temp_year, temp_mon;
             newEvent->startTime.tm_isdst = 0;
             newEvent->endTime.tm_isdst = 0;
             sscanf(line, "SUMMARY: %[^\n]", newEvent->title); /* Reads every character until -1 (EOF) */
             sscanf(line, "DTSTART:%4d%2d%2dT%2d%2d%2d%s",
                    &temp_year,
                    &temp_mon,
                    &newEvent->startTime.tm_mday,
                    &newEvent->startTime.tm_hour,
                    &newEvent->startTime.tm_min,
                    &newEvent->startTime.tm_sec,
                    leftOverGarbage);
             newEvent->startTime.tm_year = temp_year - 1900;
             newEvent->startTime.tm_mon = temp_mon - 1;
             if (sscanf(line, "DESCRIPTION:%[0-9a-zA-Z ]", leftOverGarbage) && leftOverGarbage[0] != '$') {
                 sscanf(line, "DESCRIPTION:$P%d$", &newEvent->priority);
             } else {
                 sscanf(line, "DESCRIPTION:$P%d$", &newEvent->priority);
             }
             if (newEvent->priority < 0) {
                 printf("yip");
                 newEvent->priority = 0;
             } else if (newEvent->priority > MAX_PRIORITY) {
                 printf("yap");
                 newEvent->priority = MAX_PRIORITY;
             }
             sscanf(line, "DTEND:%4d%2d%2dT%2d%2d%2d%s",
                    &temp_year,
                    &temp_mon,
                    &newEvent->endTime.tm_mday,
                    &newEvent->endTime.tm_hour,
                    &newEvent->endTime.tm_min,
                    &newEvent->endTime.tm_sec,
                    leftOverGarbage);
             newEvent->endTime.tm_year = temp_year - 1900;
             newEvent->endTime.tm_mon = temp_mon - 1;
         }
         if (strstr(line, "END:VEVENT")) {
             addEventCal(newEvent, calendar);
             isEvent = 0;
         }
     }
     calendar->numOfEvents = numOfEvents;
     return 1;
 }
References addEventCal(), calendar::file, LINE_LEN, MAX_PRIORITY, and calendar::numOfEvents.
Referenced by getCalendarSuiteGetData().
getCalendarSuiteGetFile()
int getCalendarSuiteGetFile (int argc, char * argv[], calendar * calPtrArray[])
Opens and stores file-pointer / file-path in calPtrArray.
Goes through argc number of arguments argv, if the argv is an *.ics file tries to open the file. The file-path, and file-pointer is stored in calPtrArray, for each *.ics file.
Parameters
argc number of arguments
argv arguments
calPtrArray output parameter
Returns
1 if all file locations where valid, else 0
Definition at line 14 of file getCalendarSuite.c.
{
     int i = 1;
     int k = 0;
     int validFileLocation = 1;
     do {
         if (isIcsFile(argv[i])) {
             validFileLocation = getCalendarSuiteGetFileSingle(argv[i], calPtrArray[k]);
             k++;
         }
         i++;
     } while (i < argc && validFileLocation);
     return validFileLocation;
 }
References getCalendarSuiteGetFileSingle(), and isIcsFile().
Referenced by getCalendarSuite(), test1_getCalendarSuiteGetFile(), and test2_getCalendarSuiteGetFile().
getCalendarSuiteGetFileSingle()
int getCalendarSuiteGetFileSingle (char arg[], calendar * calendar)
Tries to open arg as a file, stores the file-path and file-pointer in calendar.
Parameters
arg file-path to an *.ics file
calendar Output parameter, where file-path and file-pointer should be stored
Returns
1 if file-path was valid, else 0
Definition at line 37 of file getCalendarSuite.c.
{
     int validFileLocation = 0;
     calendar->file = fopen(arg, "r");
     strcpy(calendar->fileName, arg);
     if (calendar->file == NULL) {
         validFileLocation = 0;
     } else {
         validFileLocation = 1;
     }
     return validFileLocation;
 }
References calendar::file, and calendar::fileName.
Referenced by getCalendarSuiteGetFile(), test1_getCalendarSuiteGetFileSingle(), and test2_getCalendarSuiteGetFileSingle().
getDates()
void getDates (tm * startDate, tm * endDate)
Get the Dates object.
First we ask for a start date, and reuce the value by 1. We do this because tm_mon in the tm struct, uses months after january, so if we want the event to start in february, the input needs to be 1 because february is one month after january. We do this for the enddate for the event as well. And to end it off we print the dates and confirm the start- and end dates.
Parameters
startDate
endDate
Definition at line 76 of file getSearchParameters.c.
{
     int validInput = 0;
     tm tempStartDate = INIT_TM;
     tm tempEndDate = INIT_TM;
     do {
         printf("Enter the earliest date the event can take place in the format: dd/mm/yyyy> ");
         scanf(" %d/%d/%d", &tempStartDate.tm_mday, &tempStartDate.tm_mon, &tempStartDate.tm_year);
         tempStartDate.tm_mon--;
         tempStartDate.tm_year = tempStartDate.tm_year - EPOCH;
         validInput = isTimeValid(tempStartDate);
         fflush(stdin);
     } while (!validInput);
     do {
         printf("Enter the latest date the event can take place in the format: dd/mm/yyyy> ");
         scanf(" %d/%d/%d", &tempEndDate.tm_mday, &tempEndDate.tm_mon, &tempEndDate.tm_year);
         tempEndDate.tm_mon--;
         tempEndDate.tm_year = tempEndDate.tm_year - EPOCH;
         validInput = isTimeValid(tempEndDate);
         fflush(stdin);
     } while (!validInput);
     if (DEBUG) {
         printf("tempStartDate: %.2d/%.2d/%.4d\n", tempStartDate.tm_mday, tempStartDate.tm_mon, tempStartDate.tm_year + EPOCH);
         printf("tempEndDate: %.2d/%.2d/%.4d\n", tempEndDate.tm_mday, tempEndDate.tm_mon, tempEndDate.tm_year + EPOCH);
     }
     *startDate = tempStartDate;
     *endDate = tempEndDate;
 }
References DEBUG, EPOCH, INIT_TM, and isTimeValid().
Referenced by getSearchParameters().
getEndOfLine()
time_t getEndOfLine (const searchParameters * p)
Finds the latest time an event can take place, according to p.
Parameters
p Search parameters
Returns
Latest time an event can take place as a time_t.
Precondition
INIT_TM should be #defined as { 0, 0, 0, 1, 0, 0, 0, 0, -1 }.
Definition at line 472 of file findAvailableDates.c.
{
     tm time_tm = INIT_TM;
     time_t time;
     time_tm.tm_min = p->upperLimit.tm_min;
     time_tm.tm_hour = p->upperLimit.tm_hour;
     time_tm.tm_mday = p->endDate.tm_mday;
     time_tm.tm_mon = p->endDate.tm_mon;
     time_tm.tm_year = p->endDate.tm_year;
     time = mktime(&time_tm);
     return time;
 }
References searchParameters::endDate, INIT_TM, and searchParameters::upperLimit.
Referenced by endOfLine().
getEventBuffer()
int getEventBuffer (void)
Prompts user: Enter how much buffer time should be in beginning and end of event.
Input by user can not be under 0.
Returns
buffer entered.
Definition at line 51 of file getSearchParameters.c.
{
     int eventBuffer = 0;
     int validInput = 0;
     do {
         printf("Enter how much buffer time should be in beginning and end of event in minutes> ");
         validInput = scanf(" %d", &eventBuffer);
         fflush(stdin);
     } while (!validInput || eventBuffer < 0);
     return eventBuffer;
 }
Referenced by getSearchParameters().
getEventLen()
int getEventLen (void)
Get the Event Len object.
Here we ask for the length of the event in minutes, and check if it's a valid and positiv input we are getting. If yes, then we return the length from the function.
Returns
int
Definition at line 32 of file getSearchParameters.c.
                       {
     int eventLen = 0;
     int validInput = 0;
     do {
         printf("Enter estimated length of the event in minutes> ");
         validInput = scanf(" %d", &eventLen);
         fflush(stdin);
     } while (!validInput || eventLen < 0);
     return eventLen;
 }
Referenced by getSearchParameters().
getLimits()
void getLimits (tm * lowerLimmit, tm * upperLimit)
Get the Limits object.
Here we ask how much the event can be moved witin the same day, so only hours and minutes. We do this for both the upper- and lower limit. And at the end of the function we print, and confirm the upper- and lower limit.
Parameters
upperLimit
lowerLimmit
Definition at line 118 of file getSearchParameters.c.
{
     int validInput = 0;
     tm tempLowerLimit = INIT_TM;
     tm tempUpperLimit = INIT_TM;
     do {
         printf("Enter the earliest time the event can take place in the format: HH:MM>  ");
         scanf(" %d:%d", &tempLowerLimit.tm_hour, &tempLowerLimit.tm_min);
         validInput = isTimeValid(tempLowerLimit);
         fflush(stdin);
     } while (!validInput);
     do {
         printf("Enter the latest time the event can take place in the format: HH:MM>  ");
         scanf(" %d:%d", &tempUpperLimit.tm_hour, &tempUpperLimit.tm_min);
         validInput = isTimeValid(tempUpperLimit);
         fflush(stdin);
     } while (!validInput);
     if (DEBUG) {
         printf("%.2d:%.2d\n", tempLowerLimit.tm_hour, tempLowerLimit.tm_min);
         printf("%.2d:%.2d\n", tempUpperLimit.tm_hour, tempUpperLimit.tm_min);
     }
     *lowerLimmit = tempLowerLimit;
     *upperLimit = tempUpperLimit;
 }
References DEBUG, INIT_TM, and isTimeValid().
Referenced by getSearchParameters().
getPriority()
int getPriority (void)
Get the Priority object.
Here we ask for a priority for the event. Once the user has given us a valid input, then we return the priority from the function.
Returns
int
Definition at line 12 of file getSearchParameters.c.
                       {
     int priority = 0;
     int validInput = 0;
     do {
         printf("Enter a priority for the event> ");
         validInput = scanf(" %d", &priority);
         fflush(stdin);
     } while (!validInput || priority < 0);
     return priority;
 }
Referenced by getSearchParameters().
getSearchParameters()
void getSearchParameters (searchParameters * a)
Parameters
a
Definition at line 92 of file main.c.
{
     a->priority = getPriority();
     a->eventLen = getEventLen();
     a->buffer  = getEventBuffer();
     getDates(&a->startDate, &a->endDate);
     getLimits(&a->lowerLimit, &a->upperLimit);
     if (DEBUG) {
         printf("Priority: %d\nEventLen: %d", a->priority, a->eventLen);
     }
 }
References searchParameters::buffer, DEBUG, searchParameters::endDate, searchParameters::eventLen, getDates(), getEventBuffer(), getEventLen(), getLimits(), getPriority(), searchParameters::lowerLimit, searchParameters::priority, searchParameters::startDate, and searchParameters::upperLimit.
Referenced by main().
getStartOfLine()
time_t getStartOfLine (const searchParameters * p)
Finds the earliest time an event can take place, according to p.
Parameters
p Search parameters
Returns
Latest time an event can take place as a time_t.
Precondition
INIT_TM should be #defined as { 0, 0, 0, 1, 0, 0, 0, 0, -1 }.
Definition at line 450 of file findAvailableDates.c.
{
     tm time_tm = INIT_TM;
     time_t time;
     time_tm.tm_min = p->lowerLimit.tm_min;
     time_tm.tm_hour = p->lowerLimit.tm_hour;
     time_tm.tm_mday = p->startDate.tm_mday;
     time_tm.tm_mon = p->startDate.tm_mon;
     time_tm.tm_year = p->startDate.tm_year;
     time = mktime(&time_tm);
     return time;
 }
References INIT_TM, searchParameters::lowerLimit, and searchParameters::startDate.
Referenced by lookForFreeSlot().
goToLowerLimitNextDay()
void goToLowerLimitNextDay (time_t head, const searchParameters * p, tm * head_tm)
Sets head_tm to lowerLimit the next day.
Parameters
head head_tm in unix time
p Search paramters, where lowerLimit is defined.
[in,out] head_tm tm structure to change.
Precondition
UNIX_24H should be #defined as 60 * 60 * 24 or 86400.
Definition at line 426 of file findAvailableDates.c.
{
     head += UNIX_24H;
     *head_tm = *localtime(&head);
     goToLowerLimitThisDay(p, head_tm);
 }
References goToLowerLimitThisDay(), and UNIX_24H.
Referenced by setHeadToNextLL().
goToLowerLimitThisDay()
void goToLowerLimitThisDay (const searchParameters * p, tm * head_tm)
Sets head_tm to lowerLimit same day.
Parameters
p Search paramters, where lowerLimit is defined.
head_tm tm structure to change.
Definition at line 438 of file findAvailableDates.c.
{
     head_tm->tm_min = p->lowerLimit.tm_min;
     head_tm->tm_hour = p->lowerLimit.tm_hour;
 }
References searchParameters::lowerLimit.
Referenced by goToLowerLimitNextDay(), and setHeadToNextLL().
headWithinLimits()
int headWithinLimits (const searchParameters * p, time_t head)
Controls that an event that starts at head, and is defined by p is within limits.
Parameters
p Search paramters, where limits are defined, and where event is defined.
head Start time of event.
Returns
1 if it is within limits, else 0.
Precondition
MIN_TO_SEC should be #defined as 60.
Definition at line 325 of file findAvailableDates.c.
{
     int returnFlag = 0;
     tm tm_headStart;
     tm tm_headEnd;
     time_t headEnd;
     headEnd = head + (p->eventLen * MIN_TO_SEC) + (2 * p->buffer * MIN_TO_SEC);
     tm_headStart = *localtime(&head);
     tm_headEnd = *localtime(&headEnd);
     returnFlag += tmWithinLimits(p, &tm_headStart);
     returnFlag += tmWithinLimits(p, &tm_headEnd);
     if (returnFlag == 2) {
         returnFlag = 1;
     } else {
         returnFlag = 0;
     }
     return returnFlag;
 }
References searchParameters::buffer, searchParameters::eventLen, MIN_TO_SEC, and tmWithinLimits().
Referenced by stuckProcedure().
isIcsFile()
int isIcsFile (char arg[])
Controls that a string ends with ".ics".
Parameters
arg string to control
Returns
1 if it does end with ".ics", else 0
Definition at line 49 of file ctrlAndDoArgs.c.
{
     if ((strlen(arg)) < 5) {
         return 0;
     } else {
         return (strncmp(&arg[strlen(arg) - 4], ".ics", 4) == 0);
     }
 }
Referenced by doArg(), and getCalendarSuiteGetFile().
isLeapYear()
int isLeapYear (int tm_year)
Controls is a year is a leap year.
Parameters
tm_year year
Returns
1 if the year is a leap year, else 0
Definition at line 172 of file helperFunctions.c.
{
     if (tm_year % 100 == 0 && tm_year % 400 != 0) {
         return 0;
     } else if (tm_year % 4 == 0) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by daysInMonthFeb().
isOption()
int isOption (char arg[])
Controls if a string is considered an option from the command line.
Parameters
arg string to be controlled
Returns
1 if it is an option, else 0
Definition at line 29 of file ctrlAndDoArgs.c.
{
     if (!(strncmp(arg, "--", 2) == 0)) {
         return 0;
     } else if (strncmp(arg, "--test", 6) == 0) {
         return 1;
     } else if (strncmp(arg, "--debug", 7) == 0) {
         return 1;
     } else if (strncmp(arg, "--doNothing", 11) == 0) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by doArg().
isTimeValid()
int isTimeValid (tm time)
Controls that a time is valid in terms of minutes, hours, month number, year, month day.
The functions take leap years into account.
Parameters
time struct tm, from time.h, to be controlled
Returns
1 if time is valid, else 0
Definition at line 13 of file helperFunctions.c.
{
     int returnFlag = 0;
     returnFlag += isTimeValid_min(time.tm_min);
     returnFlag += isTimeValid_hour(time.tm_hour);
     returnFlag += isTimeValid_mon(time.tm_mon);
     returnFlag += isTimeValid_year(time.tm_year);
     returnFlag += isTimeValid_mday(time.tm_year, time.tm_mon, time.tm_mday);
     if (returnFlag == 5) {
         returnFlag = 1;
     } else {
         returnFlag = 0;
     }
     return returnFlag;
 }
References isTimeValid_hour(), isTimeValid_mday(), isTimeValid_min(), isTimeValid_mon(), and isTimeValid_year().
Referenced by getDates(), getLimits(), test10_isTimeValid(), test1_isTimeValid(), test2_isTimeValid(), test3_isTimeValid(), test4_isTimeValid(), test5_isTimeValid(), test6_isTimeValid(), test7_isTimeValid(), test8_isTimeValid(), and test9_isTimeValid().
isTimeValid_hour()
int isTimeValid_hour (int tm_hour)
Controls that tm_hour == [0, 23].
Parameters
tm_hour member of struct tm from time.h
Returns
1 if its within the boundary, else 0
Definition at line 50 of file helperFunctions.c.
{
     if (tm_hour >= 0 && tm_hour <= 23) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
isTimeValid_mday()
int isTimeValid_mday (int tm_year, int tm_mon, int tm_mday)
Controls that a month day is valid depending on the year and month.
Parameters
tm_year year
tm_mon month, january is month 0
tm_mday month day
Returns
1 if the month day is valid, else 0
Definition at line 94 of file helperFunctions.c.
{
     if (tm_mday <= daysInMonth(tm_mon, tm_year) && tm_mday > 0) {
         return 1;
     } else {
         return 0;
     }
 }
References daysInMonth().
Referenced by isTimeValid().
isTimeValid_min()
int isTimeValid_min (int tm_min)
Controls that tm_min == [0, 59].
Parameters
tm_min member of struct tm from time.h
Returns
1 if its within the boundary, else 0
Definition at line 36 of file helperFunctions.c.
{
     if (tm_min >= 0 && tm_min <= 59) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
isTimeValid_mon()
int isTimeValid_mon (int tm_mon)
Controls that tm_mon == [0, 11].
Parameters
tm_mon member of struct tm from time.h
Returns
1 if its within the boundary, else 0
Definition at line 64 of file helperFunctions.c.
{
     if (tm_mon >= 0 && tm_mon <= 11) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
isTimeValid_year()
int isTimeValid_year (int tm_year)
Controls that tm_year > 1900.
Parameters
tm_year member of struct tm from time.h
Returns
1 if its within the boundary, else 0
Definition at line 78 of file helperFunctions.c.
{
     if (tm_year >= 0) {
         return 1;
     } else {
         return 0;
     }
 }
Referenced by isTimeValid().
lookForFreeSlot()
tm lookForFreeSlot (const searchParameters * p, int arrLen, event * allEvents[])
Looks for a free time slot, defined by p, in a sorted array of pointers to events.
Iterating over allEvents, this functions looks a timeslot of lenght eventLen + buffer * 2 (in minutes). The function will keep looking until:
End of list is reached (i < arrLen && allEvents[i] != NULL) and
A date is found (dateFound.tm_year < 0)
head has not gone over endOfLine (dateFound.tm_year != eol)
Parameters
p Search parameters, controls what timeslot loofForFreeSlot should look for, and where it should look.
arrLen length of array allEvents
allEvents sorted array of pointers
Returns
If a date is found that date is returned as a tm structure. Else returns a date where .tm_year < 0.
Precondition
enum lookForFreeSlotStatus { eol = -1, endOfLine look = -2, redo = -3 }; should be in header. allEvents should be sorted in acending order by starting date.
Definition at line 152 of file findAvailableDates.c.
{
     time_t head = getStartOfLine(p);
     tm dateFound;
     int i = 0;
     dateFound.tm_year = look;
     while (i < arrLen && allEvents[i] != NULL && dateFound.tm_year < 0 && dateFound.tm_year != eol) {
         if (DEBUG) printf("Event: %s\n", allEvents[i]->title);
         dateFound = lookForFreeSlotSingle(p, allEvents[i], &head);
         if (DEBUG) {
             printf("head: ");
             print_time_t(head);
             printf("\n");
         }
         if (dateFound.tm_year != redo) {
             i++;
         }
     }
     return dateFound;
 }
References DEBUG, eol, getStartOfLine(), look, lookForFreeSlotSingle(), print_time_t(), and redo.
Referenced by findAvailableDates().
lookForFreeSlotSingle()
tm lookForFreeSlotSingle (const searchParameters * p, event * event, time_t * head)
Looks for a free time slot between head and event->startTime.
If head is at endOfLine: .tm_year in the return struct tm is set to eol. This causes lookForFreeSlot() to stop looking for an event.
Else if head is able to elongate, head elongates meaning head is set to event->endTime (in unix time). lookForFreeSlot() should then iterates to next event.
Else if head is able to swallow, head swallows meaning head is unchanged. lookForFreeSlot() should then iterates to next event.
Else if head is stuck, stuck mening it found a time slot of lenght greater than eventLen
buffer * 2, lookForFreeSlot() either does not iterate if date was not within limits as defined by p, or causes lookForFreeSlot() to stop looking as a date was found.
Parameters
p Search parameters.
event Pointer to event to compare.
[in,out] head Current head to compare and change.
Returns
If a date is found that date is returned as a tm structure. Else returns a date where .tm_year < 0.
Precondition
enum lookForFreeSlotStatus { eol = -1, endOfLine look = -2, redo = -3 }; should be in header.
Definition at line 199 of file findAvailableDates.c.
{
     time_t eventStartTimeUnix = mktime(&event->startTime);
     time_t eventEndTimeUnix = mktime(&event->endTime);
     tm dateFound;
     dateFound.tm_year = look;
     if (endOfLine(p, *head)) {
         if (DEBUG) printf("endOfLine\n");
         dateFound.tm_year = eol;
     } else if (canElongate(eventStartTimeUnix, eventEndTimeUnix, *head, p)) {
         if (DEBUG) printf("elongate\n");
         *head = eventEndTimeUnix;
     } else if (canSwallow(eventStartTimeUnix, eventEndTimeUnix, *head)) {
         if (DEBUG) printf("swallow\n");
     } else if (stuck(eventStartTimeUnix, *head, p)) {
         dateFound = stuckProcedure(p, head);
     }
     return dateFound;
 }
References canElongate(), canSwallow(), DEBUG, endOfLine(), event::endTime, eol, look, event::startTime, stuck(), and stuckProcedure().
Referenced by lookForFreeSlot().
mallocCalendarSuite()
void mallocCalendarSuite (int n, calendarSuite * calendarSuite)
Allocates memory for an calendarSuite.calPtrArray of length n.
Terminates the program if it fails to allocate memory.
Parameters
n length of array
calendarSuite output parameter, calendarSuite to be allocated memory
Definition at line 72 of file main.c.
{
     int i = 0;
     calendarSuite->Arraylen = n;
     calendarSuite->calPtrArray = (calendar **)malloc((n) * sizeof(calendar *));
     errorHandling(calendarSuite->calPtrArray == NULL, "!!!FAILED TO ALLOCATE MEMORY STEP 1!!!");
     while (i < n) {
         calendarSuite->calPtrArray[i] = (calendar *)malloc(sizeof(calendar));
         calendarSuite->calPtrArray[i]->firstEvent = NULL;
         errorHandling(calendarSuite->calPtrArray[i] == NULL, "!!!FAILED TO ALLOCATE MEMORY STEP 2!!!");
         i++;
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, errorHandling(), and calendar::firstEvent.
Referenced by main(), test1_getCalendarSuiteGetFile(), and test2_getCalendarSuiteGetFile().
mallocEventLink()
eventLink* mallocEventLink (event * event, eventLink * pointer)
Creates a new eventLink.
Allocates space on the heap for a new evenLink, makes the eventLink point to event, and pointer.
Parameters
event Event this link should point to.
pointer Next link this link should point to.
Returns
Pointer to the new eventLink that has been created.
Definition at line 187 of file getCalendarSuite.c.
{
     eventLink *newLink;
     newLink = (eventLink *)malloc(sizeof(eventLink));
     newLink->currentEvent = event;
     /*newLink->nextEventLink = (eventLink *)malloc(sizeof(eventLink));*/ /* <----- this is unnecessary*/
     newLink->nextEventLink = pointer;
     return newLink;
 }
References eventLink::currentEvent, and eventLink::nextEventLink.
Referenced by addEventCal().
overUpperLimit()
int overUpperLimit (const searchParameters * p, const tm * head_tm)
Controls if head_tm is over upperLimit.
Parameters
p Search paramters, where upperLimit is defined.
head_tm tm structure to control
Returns
1 if it is, else 0
Definition at line 391 of file findAvailableDates.c.
{
     if (head_tm->tm_hour > p->upperLimit.tm_hour) {
         return 1;
     } else if (head_tm->tm_hour == p->upperLimit.tm_hour && head_tm->tm_min > p->upperLimit.tm_min) {
         return 1;
     } else {
         return 0;
     }
 }
References searchParameters::upperLimit.
print_time_t()
void print_time_t (time_t time)
Converts a time_t to a tm structure, prints the tm structure.
Parameters
time time_t to print.
Precondition
EPOCH should be #defined as 1900.
Definition at line 493 of file findAvailableDates.c.
{
     tm *time_tm = localtime(&time);
     printf("%.2d/%.2d/%.2d - %.2d:%.2d\n",
            time_tm->tm_mday,
            time_tm->tm_mon + 1,
            time_tm->tm_year + EPOCH,
            time_tm->tm_hour,
            time_tm->tm_min);
 }
References EPOCH.
Referenced by lookForFreeSlot().
printCalendar()
void printCalendar (const calendar * calendar)
Prints data stored in the linked list of eventLinks pointed to by calendar.
Parameters
calendar Pointer to calendar from where the linked list should be printed.
Definition at line 224 of file helperFunctions.c.
{
     eventLink *cursor;
     int i = 1;
     cursor = calendar->firstEvent;
     printf("    EVENT: 0\n");
     printEvent(cursor->currentEvent);
     while (cursor->nextEventLink != NULL) {
         cursor = cursor->nextEventLink;
         printf("    EVENT: %d\n", i);
         printEvent(cursor->currentEvent);
         i++;
     }
     printf("Number of events: %d\n", calendar->numOfEvents);
 }
References eventLink::currentEvent, calendar::firstEvent, eventLink::nextEventLink, calendar::numOfEvents, and printEvent().
Referenced by printCalendars().
printCalendars()
void printCalendars (calendarSuite * calendarSuite)
Prints all data stored in calendarSuite.
Parameters
calendarSuite Suite to print.
Definition at line 200 of file helperFunctions.c.
{
     int i;
     for (i = 0; i < calendarSuite->Arraylen; i++) {
         printMetadataCalendar(calendarSuite->calPtrArray[i]);
         printCalendar(calendarSuite->calPtrArray[i]);
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, printCalendar(), and printMetadataCalendar().
Referenced by getCalendarSuite().
printEvent()
void printEvent (const event * a)
Prints all data from one single event structure.
Parameters
a Pointer to event structure.
Definition at line 247 of file helperFunctions.c.
{
     printf("    SUMMARY: %s\n", a->title);
     printf("    DTSTART: %.2d/%.2d/%.2d Time: %.2d:%.2d:%.2d\n",
            a->startTime.tm_year + 1900,
            a->startTime.tm_mon + 1,
            a->startTime.tm_mday,
            a->startTime.tm_hour,
            a->startTime.tm_min,
            a->startTime.tm_sec);
     printf("    DTEND:   %.2d/%.2d/%.2d Time: %.2d:%.2d:%.2d\n",
            a->endTime.tm_year + 1900,
            a->endTime.tm_mon + 1,
            a->endTime.tm_mday,
            a->endTime.tm_hour,
            a->endTime.tm_min,
            a->endTime.tm_sec);
     printf("    Priority: %d\n\n", a->priority);
 }
References event::endTime, event::priority, event::startTime, and event::title.
Referenced by printCalendar(), and printEventPtrArray().
printEventPtrArray()
void printEventPtrArray (event * allEvents[], int n)
Prints all event data in a given array of pointer to events of length n.
Parameters
allEvents pointer to array of pointers to events
n length of array to be printed
Definition at line 125 of file findAvailableDates.c.
{
     int i;
     for (i = 0; i < n; i++) {
         if (allEvents[i] != NULL) {
             printEvent(allEvents[i]);
         }
     }
 }
References printEvent().
Referenced by findAvailableDates().
printMetadataCalendar()
void printMetadataCalendar (const calendar * calendar)
Prints all "readable" data in a calendar structure.
Parameters
calendar Calendar structure to print.
Definition at line 213 of file helperFunctions.c.
{
     printf("calName: %s\n", calendar->calName);
     printf("fileName: %s\n", calendar->fileName);
     printf("numOfEvents: %d\n\n", calendar->numOfEvents);
 }
References calendar::calName, calendar::fileName, and calendar::numOfEvents.
Referenced by printCalendars(), and printMetadataCalendarSuite().
printMetadataCalendarSuite()
void printMetadataCalendarSuite (calendarSuite calendarSuite)
Prints all data stored in calendar structs pointed to by calendarSuite.calPtrArray.
Parameters
calendarSuite Suite from where the data should be printed from.
Definition at line 271 of file helperFunctions.c.
{
     int i;
     for (i = 0; i < calendarSuite.Arraylen; i++) {
         printf("\nCALENDAR %d: \n", i);
         printMetadataCalendar(calendarSuite.calPtrArray[i]);
     }
 }
References calendarSuite::Arraylen, calendarSuite::calPtrArray, and printMetadataCalendar().
runAllTests()
void runAllTests (void)
Definition at line 5 of file allTests.c.
{
     CuString *output = CuStringNew();
     CuSuite *suite = CuSuiteNew();
     CuSuiteAddSuite(suite, suite_ctrlAndDoArgs());
     CuSuiteAddSuite(suite, suite_getCalendarSuite());
     CuSuiteAddSuite(suite, suite_sharedFunctions());
     CuSuiteRun(suite);
     CuSuiteSummary(suite, output);
     CuSuiteDetails(suite, output);
     printf("%s\n", output->buffer);
 }
References CuString::buffer, CuStringNew(), CuSuiteAddSuite(), CuSuiteDetails(), CuSuiteNew(), CuSuiteRun(), CuSuiteSummary(), suite_ctrlAndDoArgs(), suite_getCalendarSuite(), and suite_sharedFunctions().
Referenced by doOption().
setHeadToNextLL()
void setHeadToNextLL (const searchParameters * p, time_t * head)
Sets head to be the next lowerLimit.
Parameters
p Search paramters, where lowerLimit is defined.
[in,out] head Head to set.
Definition at line 372 of file findAvailableDates.c.
{
     tm head_tm = *localtime(head);
     if (underLowerLimit(p, &head_tm)) {
         goToLowerLimitThisDay(p, &head_tm);
     } else {
         goToLowerLimitNextDay(*head, p, &head_tm);
     }
     *head = mktime(&head_tm);
 }
References goToLowerLimitNextDay(), goToLowerLimitThisDay(), and underLowerLimit().
Referenced by stuckProcedure().
stuck()
int stuck (time_t eventStartTimeUnix, time_t head, const searchParameters * p)
Controls if head is considered stuck.
Head is considered stuck if head is less than evenStartTimeUnix and the time between head and eventStartTimeUnix is greater or equal to: eventLen + buffer * 2 (unix time).
Parameters
eventStartTimeUnix Start time(unix) for an event.
head Head to control.
p Search parameters, where eventLen and buffer are contained.
Returns
1 if head is stuck, else 0.
Precondition
MIN_TO_SEC should be #defined as 60.
Definition at line 283 of file findAvailableDates.c.
{
     return ((head < eventStartTimeUnix) && ((eventStartTimeUnix - head) >= ((p->eventLen * MIN_TO_SEC) + (2 * p->buffer * MIN_TO_SEC))));
 }
References searchParameters::buffer, searchParameters::eventLen, and MIN_TO_SEC.
Referenced by lookForFreeSlotSingle().
stuckProcedure()
tm stuckProcedure (const searchParameters * p, time_t * head)
Runs the procedure corresponding to when head is considered stuck.
Checks if an event, as defined by p, starting at head is within limits, if this is the case the date is returned. Else head is set to the next lowerLimit, and returns tm date where .tm_year = redo.
Parameters
p Search parameters.
[in,out] head time_t to do the procedure on.
Returns
A valid tm time if a date is found within limits defined in p. Else if the date found is invalid i.e. not within the limits defined in p, returns tm date where .tm_year = redo.
Precondition
MIN_TO_SEC should be #defined as 60. enum redo should be equal to -3.
Definition at line 301 of file findAvailableDates.c.
{
     tm dateFound;
     if (headWithinLimits(p, *head)) {
         if (DEBUG) printf("found date\n");
         *head += p->buffer * MIN_TO_SEC;
         dateFound = *localtime(head);
     } else {
         if (DEBUG) printf("going to next lowerLimit\n");
         setHeadToNextLL(p, head);
         dateFound.tm_year = redo;
     }
     return dateFound;
 }
References searchParameters::buffer, DEBUG, headWithinLimits(), MIN_TO_SEC, redo, and setHeadToNextLL().
Referenced by lookForFreeSlotSingle().
suite_ctrlAndDoArgs()
CuSuite* suite_ctrlAndDoArgs (void)
Definition at line 43 of file allTests.c.
{
     CuSuite *suite = CuSuiteNew();
     SUITE_ADD_TEST(suite, test1_doArg);
     SUITE_ADD_TEST(suite, test2_doArg);
     SUITE_ADD_TEST(suite, test3_doArg);
     return suite;
 }
References CuSuiteNew(), SUITE_ADD_TEST, test1_doArg(), test2_doArg(), and test3_doArg().
Referenced by runAllTests().
suite_getCalendarSuite()
CuSuite* suite_getCalendarSuite (void)
Definition at line 97 of file allTests.c.
{
     CuSuite *suite = CuSuiteNew();
     SUITE_ADD_TEST(suite, test1_getCalendarSuiteGetFile);
     SUITE_ADD_TEST(suite, test2_getCalendarSuiteGetFile);
     SUITE_ADD_TEST(suite, test1_getCalendarSuiteGetFileSingle);
     SUITE_ADD_TEST(suite, test2_getCalendarSuiteGetFileSingle);
     return suite;
 }
References CuSuiteNew(), SUITE_ADD_TEST, test1_getCalendarSuiteGetFile(), test1_getCalendarSuiteGetFileSingle(), test2_getCalendarSuiteGetFile(), and test2_getCalendarSuiteGetFileSingle().
Referenced by runAllTests().
suite_sharedFunctions()
CuSuite* suite_sharedFunctions (void)
Definition at line 179 of file allTests.c.
{
     CuSuite *suite = CuSuiteNew();
     SUITE_ADD_TEST(suite, test1_isTimeValid);
     SUITE_ADD_TEST(suite, test2_isTimeValid);
     SUITE_ADD_TEST(suite, test3_isTimeValid);
     SUITE_ADD_TEST(suite, test4_isTimeValid);
     SUITE_ADD_TEST(suite, test5_isTimeValid);
     SUITE_ADD_TEST(suite, test6_isTimeValid);
     SUITE_ADD_TEST(suite, test7_isTimeValid);
     SUITE_ADD_TEST(suite, test8_isTimeValid);
     SUITE_ADD_TEST(suite, test9_isTimeValid);
     SUITE_ADD_TEST(suite, test10_isTimeValid);
     return suite;
 }
References CuSuiteNew(), SUITE_ADD_TEST, test10_isTimeValid(), test1_isTimeValid(), test2_isTimeValid(), test3_isTimeValid(), test4_isTimeValid(), test5_isTimeValid(), test6_isTimeValid(), test7_isTimeValid(), test8_isTimeValid(), and test9_isTimeValid().
Referenced by runAllTests().
test10_isTimeValid()
void test10_isTimeValid (CuTest * tc)
Definition at line 172 of file allTests.c.
{
     tm input = {0, 61, 25, 1, 0, 2000, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test1_doArg()
void test1_doArg (CuTest * tc)
Definition at line 22 of file allTests.c.
{
     char input[] = "test";
     int actual = doArg(input);
     int expected = invalid;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, doArg(), and invalid.
Referenced by suite_ctrlAndDoArgs().
test1_getCalendarSuiteGetFile()
void test1_getCalendarSuiteGetFile (CuTest * tc)
Definition at line 54 of file allTests.c.
{
     int actual;
     int expected;
     int input1 = 4;
     char *input2[] = {"a", ".\\sample-ics-files\\cal1.ics", ".\\sample-ics-files\\cal2.ics", ".\\sample-ics-files\\cal3.ics"};
     calendarSuite input3;
     mallocCalendarSuite(3, &input3);
     actual = getCalendarSuiteGetFile(input1, input2, input3.calPtrArray);
     expected = 1;
     free(input3.calPtrArray);
     CuAssertIntEquals(tc, expected, actual);
 }
References calendarSuite::calPtrArray, CuAssertIntEquals, getCalendarSuiteGetFile(), and mallocCalendarSuite().
Referenced by suite_getCalendarSuite().
test1_getCalendarSuiteGetFileSingle()
void test1_getCalendarSuiteGetFileSingle (CuTest * tc)
Definition at line 81 of file allTests.c.
{
     char input1[] = ".\\sample-ics-files\\cal1.ics";
     calendar input2;
     int actual = getCalendarSuiteGetFileSingle(input1, &input2);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and getCalendarSuiteGetFileSingle().
Referenced by suite_getCalendarSuite().
test1_isTimeValid()
void test1_isTimeValid (CuTest * tc)
Definition at line 109 of file allTests.c.
{
     tm input = INIT_TM;
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, INIT_TM, and isTimeValid().
Referenced by suite_sharedFunctions().
test2_doArg()
void test2_doArg (CuTest * tc)
Definition at line 29 of file allTests.c.
{
     char input[] = "--doNothing";
     int actual = doArg(input);
     int expected = option;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, doArg(), and option.
Referenced by suite_ctrlAndDoArgs().
test2_getCalendarSuiteGetFile()
void test2_getCalendarSuiteGetFile (CuTest * tc)
Definition at line 67 of file allTests.c.
{
     int actual;
     int expected;
     int input1 = 4;
     char *input2[] = {"a", ".\\sample-ics-files\\notAValidFileLocation.ics", ".\\sample-ics-files\\cal2.ics", ".\\sample-ics-files\\cal3.ics"};
     calendarSuite input3;
     mallocCalendarSuite(3, &input3);
     actual = getCalendarSuiteGetFile(input1, input2, input3.calPtrArray);
     expected = 0;
     free(input3.calPtrArray);
     CuAssertIntEquals(tc, expected, actual);
 }
References calendarSuite::calPtrArray, CuAssertIntEquals, getCalendarSuiteGetFile(), and mallocCalendarSuite().
Referenced by suite_getCalendarSuite().
test2_getCalendarSuiteGetFileSingle()
void test2_getCalendarSuiteGetFileSingle (CuTest * tc)
Definition at line 89 of file allTests.c.
{
     char input1[] = ".\\sample-ics-files\\notAValidFileLocation.ics";
     calendar input2;
     int actual = getCalendarSuiteGetFileSingle(input1, &input2);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and getCalendarSuiteGetFileSingle().
Referenced by suite_getCalendarSuite().
test2_isTimeValid()
void test2_isTimeValid (CuTest * tc)
Definition at line 116 of file allTests.c.
{
     tm input = {0, 25, 20, 16, 4, 2009, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test3_doArg()
void test3_doArg (CuTest * tc)
Definition at line 36 of file allTests.c.
{
     char input[] = "*.ics";
     int actual = doArg(input);
     int expected = icsFile;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, doArg(), and icsFile.
Referenced by suite_ctrlAndDoArgs().
test3_isTimeValid()
void test3_isTimeValid (CuTest * tc)
Definition at line 123 of file allTests.c.
{
     tm input = {0, 0, 0, 29, 2, 2004, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test4_isTimeValid()
void test4_isTimeValid (CuTest * tc)
Definition at line 130 of file allTests.c.
{
     tm input = {0, 0, 0, 30, 1, 2004, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test5_isTimeValid()
void test5_isTimeValid (CuTest * tc)
Definition at line 137 of file allTests.c.
{
     tm input = {0, 0, 0, 28, 1, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test6_isTimeValid()
void test6_isTimeValid (CuTest * tc)
Definition at line 144 of file allTests.c.
{
     tm input = {0, 0, 0, 31, 0, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test7_isTimeValid()
void test7_isTimeValid (CuTest * tc)
Definition at line 151 of file allTests.c.
{
     tm input = {0, 0, 0, 32, 0, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test8_isTimeValid()
void test8_isTimeValid (CuTest * tc)
Definition at line 158 of file allTests.c.
{
     tm input = {0, 0, 0, 30, 3, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 1;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
test9_isTimeValid()
void test9_isTimeValid (CuTest * tc)
Definition at line 165 of file allTests.c.
{
     tm input = {0, 0, 0, 31, 3, 2005, 0, 0, -1};
     int actual = isTimeValid(input);
     int expected = 0;
     CuAssertIntEquals(tc, expected, actual);
 }
References CuAssertIntEquals, and isTimeValid().
Referenced by suite_sharedFunctions().
tmWithinLimits()
int tmWithinLimits (const searchParameters * p, const tm * time)
Controls that time is within lowerLimit and upperLimit defined in p.
Parameters
p Search paramters, where lowerLimit and upperLimit is defined.
time tm struct to control.
Returns
1 if within the limits, else 0.
Definition at line 355 of file findAvailableDates.c.
{
     if (time->tm_hour > p->lowerLimit.tm_hour && time->tm_hour < p->upperLimit.tm_hour) {
         return 1;
     } else if ((time->tm_hour == p->lowerLimit.tm_hour && time->tm_min >= p->lowerLimit.tm_min) ||
                (time->tm_hour == p->upperLimit.tm_hour && time->tm_min <= p->upperLimit.tm_min)) {
         return 1;
     } else {
         return 0;
     }
 }
References searchParameters::lowerLimit, and searchParameters::upperLimit.
Referenced by headWithinLimits().
underLowerLimit()
int underLowerLimit (const searchParameters * p, const tm * head_tm)
Controls if head_tm is under lowerLimit.
Parameters
p Search paramters, where lowerLimit is defined.
head_tm tm structure to control
Returns
1 if it is, else 0
Definition at line 408 of file findAvailableDates.c.
{
     if (head_tm->tm_hour < p->lowerLimit.tm_hour) {
         return 1;
     } else if (head_tm->tm_hour == p->lowerLimit.tm_hour && head_tm->tm_min < p->lowerLimit.tm_min) {
         return 1;
     } else {
         return 0;
     }
 }
References searchParameters::lowerLimit.
Referenced by setHeadToNextLL().